const fs = require('fs');

const path = './app/context/LanguageContext.tsx';
let content = fs.readFileSync(path, 'utf8');

const newTranslations = {
  en: `    // Footer
    "all_the_books": "All the books in the world",
    "all_about_shopping": "All about shopping",
    "delivery_payment": "Delivery and payment",
    "terms_conditions": "Terms and conditions",
    "about_the_shop": "About the shop",
    "who_we_are": "Who we are",
    "contacts": "Contacts",
    "books_sustainability": "Books sustainability",
    "for_customers": "For customers",
    "loyalty_programme": "Loyalty programme",
    "order_status": "Order status",
    "returns_complaints": "Returns / Complaints",
    "lets_stay_together": "Let's stay together",
    
    // HeroSection
    "buy_book": "Buy book",
    "video_btn": "Video",
    
    // FeaturesBar
    "23_million_titles": "23 million titles",
    "in_150_languages": "in 150+ languages",
    "great_prices": "Great prices",
    "always_up_to_date": "always up-to-date",
    "libroamanto_club": "LIBROAMANTO club",
    "full_of_gifts": "full of gifts",
    "2_million_customers": "2 million customers",
    "served_every_year": "served every year",
    
    // Categories
    "explore_categories": "Explore Categories",
    "classic_modern_print": "Classic and Modern Print",
    "digital_reading_exp": "Digital Reading Experience",
    "listen_to_stories": "Listen to Your Stories",
    "gifts_category": "Gifts",
    "special_items_lovers": "Special Items for Lovers",
    "view_collection": "View Collection",

    // Home sections
    "new_arrivals": "New Arrivals",
    "freshly_added": "Freshly added to our collection",
    "bestsellers": "Bestsellers",
    "most_loved_books": "Most loved books by our readers",
    "book_set_of_month": "Book Set of the Month",
    "carefully_selected": "Carefully selected books for this month",
    "world_literature": "World Literature",
    "timeless_classics": "Timeless classics from around the globe",
    "only": "Only",
    "left": "left!",
    "unknown_author": "Unknown Author",

    // PromoBanner
    "join_the": "Join the",
    "club": "Club",
    "promo_desc": "Get exclusive discounts, early access to new releases, and free shipping on your first order!",
    "enter_email": "Enter your email address",
    "join_now": "Join Now",
    "promo_terms": "By joining, you agree to our Terms & Conditions and Privacy Policy",

    // AI Widget
    "ai_greeting": "Hi there! 📚 I'm blendartbook AI, your personal book assistant. I can help you discover amazing books, recommend reads based on your taste, or answer any questions about our library. What are you looking for today?",
    "recommend_book": "📖 Recommend a book",
    "popular_genres": "🎭 Popular genres",
    "gift_ideas": "🎁 Gift ideas",
    "ask_me_about": "Ask me about books...",
    "powered_by": "Powered by blendartbook AI ✨"`,

  bg: `    "all_the_books": "Всички книги на света",
    "all_about_shopping": "Всичко за пазаруването",
    "delivery_payment": "Доставка и плащане",
    "terms_conditions": "Условия за ползване",
    "about_the_shop": "За магазина",
    "who_we_are": "Кои сме ние",
    "contacts": "Контакти",
    "books_sustainability": "Устойчивост на книгите",
    "for_customers": "За клиенти",
    "loyalty_programme": "Програма за лоялност",
    "order_status": "Статус на поръчката",
    "returns_complaints": "Връщане / Оплаквания",
    "lets_stay_together": "Нека останем заедно",
    
    "buy_book": "Купи книга",
    "video_btn": "Видео",
    
    "23_million_titles": "23 милиона заглавия",
    "in_150_languages": "на 150+ езика",
    "great_prices": "Страхотни цени",
    "always_up_to_date": "винаги актуални",
    "libroamanto_club": "Клуб LIBROAMANTO",
    "full_of_gifts": "пълен с подаръци",
    "2_million_customers": "2 милиона клиенти",
    "served_every_year": "обслужвани всяка година",
    
    "explore_categories": "Разгледайте категориите",
    "classic_modern_print": "Класически и модерен печат",
    "digital_reading_exp": "Дигитално четене",
    "listen_to_stories": "Слушайте историите си",
    "gifts_category": "Подаръци",
    "special_items_lovers": "Специални артикули за влюбени",
    "view_collection": "Вижте колекцията",

    "new_arrivals": "Нови предложения",
    "freshly_added": "Току-що добавени към нашата колекция",
    "bestsellers": "Бестселъри",
    "most_loved_books": "Най-обичаните книги от нашите читатели",
    "book_set_of_month": "Книжен комплект на месеца",
    "carefully_selected": "Внимателно подбрани книги за този месец",
    "world_literature": "Световна литература",
    "timeless_classics": "Вечни класики от цял свят",
    "only": "Само",
    "left": "останали!",
    "unknown_author": "Неизвестен автор",

    "join_the": "Присъединете се към",
    "club": "клуб",
    "promo_desc": "Получете ексклузивни отстъпки, ранен достъп до нови издания и безплатна доставка за първата си поръчка!",
    "enter_email": "Въведете вашия имейл адрес",
    "join_now": "Присъедини се сега",
    "promo_terms": "С присъединяването си се съгласявате с нашите Условия за ползване и Политика за поверителност",

    "ai_greeting": "Здравейте! 📚 Аз съм AI на blendartbook, вашият личен асистент за книги. Мога да ви помогна да откриете невероятни книги, да препоръчам четива въз основа на вашия вкус или да отговоря на всякакви въпроси относно нашата библиотека. Какво търсите днес?",
    "recommend_book": "📖 Препоръчай книга",
    "popular_genres": "🎭 Популярни жанрове",
    "gift_ideas": "🎁 Идеи за подаръци",
    "ask_me_about": "Попитайте ме за книги...",
    "powered_by": "Задвижвано от blendartbook AI ✨"`,

  tr: `    "all_the_books": "Dünyadaki tüm kitaplar",
    "all_about_shopping": "Alışveriş hakkında her şey",
    "delivery_payment": "Teslimat ve ödeme",
    "terms_conditions": "Şartlar ve koşullar",
    "about_the_shop": "Mağaza hakkında",
    "who_we_are": "Biz kimiz",
    "contacts": "İletişim",
    "books_sustainability": "Kitapların sürdürülebilirliği",
    "for_customers": "Müşteriler için",
    "loyalty_programme": "Sadakat programı",
    "order_status": "Sipariş durumu",
    "returns_complaints": "İadeler / Şikayetler",
    "lets_stay_together": "Birlikte kalalım",
    
    "buy_book": "Kitap al",
    "video_btn": "Video",
    
    "23_million_titles": "23 milyon kitap",
    "in_150_languages": "150'den fazla dilde",
    "great_prices": "Harika fiyatlar",
    "always_up_to_date": "her zaman güncel",
    "libroamanto_club": "LIBROAMANTO kulübü",
    "full_of_gifts": "hediyelerle dolu",
    "2_million_customers": "2 milyon müşteri",
    "served_every_year": "her yıl hizmet verilen",
    
    "explore_categories": "Kategorileri Keşfet",
    "classic_modern_print": "Klasik ve Modern Baskı",
    "digital_reading_exp": "Dijital Okuma Deneyimi",
    "listen_to_stories": "Hikayelerinizi Dinleyin",
    "gifts_category": "Hediyeler",
    "special_items_lovers": "Aşıklar için Özel Ürünler",
    "view_collection": "Koleksiyonu Gör",

    "new_arrivals": "Yeni Gelenler",
    "freshly_added": "Koleksiyonumuza yeni eklenenler",
    "bestsellers": "Çok Satanlar",
    "most_loved_books": "Okurlarımız tarafından en çok sevilen kitaplar",
    "book_set_of_month": "Ayın Kitap Seti",
    "carefully_selected": "Bu ay için özenle seçilmiş kitaplar",
    "world_literature": "Dünya Edebiyatı",
    "timeless_classics": "Dünyanın dört bir yanından zamansız klasikler",
    "only": "Sadece",
    "left": "kaldı!",
    "unknown_author": "Bilinmeyen Yazar",

    "join_the": "Katıl",
    "club": "Kulübüne",
    "promo_desc": "Özel indirimler, yeni çıkanlara erken erişim ve ilk siparişinizde ücretsiz kargo fırsatı yakalayın!",
    "enter_email": "E-posta adresinizi girin",
    "join_now": "Şimdi Katıl",
    "promo_terms": "Katılarak, Şartlar ve Koşullarımızı ve Gizlilik Politikamızı kabul etmiş olursunuz",

    "ai_greeting": "Merhaba! 📚 Ben blendartbook AI, kişisel kitap asistanınız. Harika kitaplar keşfetmenize, zevkinize göre kitap önermeme veya kütüphanemiz hakkındaki sorularınızı yanıtlamama yardımcı olabilirim. Bugün ne arıyorsunuz?",
    "recommend_book": "📖 Kitap öner",
    "popular_genres": "🎭 Popüler türler",
    "gift_ideas": "🎁 Hediye fikirleri",
    "ask_me_about": "Bana kitaplar hakkında soru sor...",
    "powered_by": "blendartbook AI tarafından desteklenmektedir ✨"`,

  ro: `    "all_the_books": "Toate cărțile din lume",
    "all_about_shopping": "Totul despre cumpărături",
    "delivery_payment": "Livrare și plată",
    "terms_conditions": "Termeni și condiții",
    "about_the_shop": "Despre magazin",
    "who_we_are": "Cine suntem",
    "contacts": "Contact",
    "books_sustainability": "Sustenabilitatea cărților",
    "for_customers": "Pentru clienți",
    "loyalty_programme": "Program de loialitate",
    "order_status": "Starea comenzii",
    "returns_complaints": "Retururi / Reclamații",
    "lets_stay_together": "Să rămânem împreună",
    
    "buy_book": "Cumpără carte",
    "video_btn": "Video",
    
    "23_million_titles": "23 milioane de titluri",
    "in_150_languages": "în 150+ limbi",
    "great_prices": "Prețuri excelente",
    "always_up_to_date": "mereu actualizate",
    "libroamanto_club": "Clubul LIBROAMANTO",
    "full_of_gifts": "plin de cadouri",
    "2_million_customers": "2 milioane de clienți",
    "served_every_year": "serviți în fiecare an",
    
    "explore_categories": "Explorează categoriile",
    "classic_modern_print": "Tipărit clasic și modern",
    "digital_reading_exp": "Experiență de citire digitală",
    "listen_to_stories": "Ascultă poveștile tale",
    "gifts_category": "Cadouri",
    "special_items_lovers": "Articole speciale pentru îndrăgostiți",
    "view_collection": "Vezi colecția",

    "new_arrivals": "Noutăți",
    "freshly_added": "Proaspăt adăugate în colecția noastră",
    "bestsellers": "Bestselleruri",
    "most_loved_books": "Cele mai iubite cărți de cititorii noștri",
    "book_set_of_month": "Setul de cărți al lunii",
    "carefully_selected": "Cărți selectate cu atenție pentru luna aceasta",
    "world_literature": "Literatură universală",
    "timeless_classics": "Clasici atemporali din întreaga lume",
    "only": "Doar",
    "left": "rămase!",
    "unknown_author": "Autor necunoscut",

    "join_the": "Alătură-te",
    "club": "Clubului",
    "promo_desc": "Obține reduceri exclusive, acces anticipat la noi lansări și livrare gratuită la prima ta comandă!",
    "enter_email": "Introdu adresa ta de email",
    "join_now": "Alătură-te acum",
    "promo_terms": "Prin înscriere, ești de acord cu Termenii și Condițiile și cu Politica de confidențialitate",

    "ai_greeting": "Salut! 📚 Sunt blendartbook AI, asistentul tău personal pentru cărți. Te pot ajuta să descoperi cărți uimitoare, să îți recomand lecturi în funcție de gustul tău sau să îți răspund la orice întrebare despre biblioteca noastră. Ce cauți astăzi?",
    "recommend_book": "📖 Recomandă o carte",
    "popular_genres": "🎭 Genuri populare",
    "gift_ideas": "🎁 Idei de cadouri",
    "ask_me_about": "Întreabă-mă despre cărți...",
    "powered_by": "Powered by blendartbook AI ✨"`
};

['en', 'bg', 'tr', 'ro'].forEach(lang => {
    // Find the end of the language block and insert new translations
    const regex = new RegExp(`(${lang}: \\{[\\s\\S]*?)(\\n  \\},)`);
    content = content.replace(regex, `$1,\n${newTranslations[lang]}$2`);
});

fs.writeFileSync(path, content, 'utf8');
