"use client";

import { createContext, useContext, useState, useEffect, useCallback, ReactNode } from "react";

// --- SUPPORTED LANGUAGES ---
export type Language = "en" | "bg" | "tr" | "ro";

export interface LanguageOption {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: "tr", name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷" },
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "ro", name: "Romanian", nativeName: "Română", flag: "🇷🇴" },
  { code: "bg", name: "Bulgarian", nativeName: "Български", flag: "🇧🇬" },
];

// --- TRANSLATION DICTIONARIES ---
type TranslationKey = string;
type Translations = Record<Language, Record<TranslationKey, string>>;

const translations: Translations = {
  en: {
    // Top bar
    "check_order_status": "Check order status",
    "free_delivery": "Free delivery over €30",
    
    // Search
    "search_placeholder": "Search books, authors, categories...",
    "search": "Search",
    
    // Nav
    "books": "Books",
    "art": "Art",
    "handmade": "Handmade",
    "ebooks": "E-books",
    "audiobooks": "Audiobooks",
    "other_products": "Other products",
    "gift_tips": "Gift tips",
    "gift_voucher": "Gift voucher",
    "cart": "Cart",
    
    // Auth
    "hi": "Hi",
    
    // Dropdown titles
    "books_title": "16 386 577 books in 175 languages",
    "ebooks_title": "1 245 000 e-books to download",
    "audiobooks_title": "450 000 audiobooks for your ears",
    "art_title": "Explore Unique Art Pieces",
    "help_text": "Don't know what to choose? We are here to help!",
    "buy_now": "Buy now",

    // Book languages
    "books_in_english": "Books in English",
    "books_in_turkish": "Books in Turkish",
    "books_in_romanian": "Books in Romanian",
    "books_in_bulgarian": "Books in Bulgarian",

    // Ebook languages
    "ebooks_in_turkish": "E-books in Turkish",
    "ebooks_in_english": "E-books in English",
    "ebooks_in_romanian": "E-books in Romanian",
    "ebooks_in_bulgarian": "E-books in Bulgarian",

    // Audiobook languages
    "audiobooks_in_turkish": "Audiobooks in Turkish",
    "audiobooks_in_english": "Audiobooks in English",
    "audiobooks_in_romanian": "Audiobooks in Romanian",
    "audiobooks_in_bulgarian": "Audiobooks in Bulgarian",

    // Other products
    "calendar_diary": "Calendar/Diary",
    "audio": "Audio",
    "game_toy": "Game/Toy",
    "video": "Video",
    "printed_items": "Printed items",
    "stationery": "Stationery",
    "digital": "Digital",

    // Gift categories
    "gifts_for_women": "Gifts for women",
    "gifts_for_men": "Gifts for men",
    "gifts_for_girls": "Gifts for girls",
    "gifts_for_boys": "Gifts for boys",
    "gifts_for_children": "Gifts for children",

    // Art categories
    "painting": "Painting",
    "sculpture": "Sculpture",
    "music": "Music",
    "crafts": "Crafts",

    // Hero / Home
    "be_whoever": "Be Whoever",
    "worlds_widest_selection": "THE WORLD'S WIDEST SELECTION OF BOOKS",
    // Footer
    "all_the_books": "All the books in the world",
    "all_about_shopping": "All about shopping",
    "delivery_payment": "Delivery and payment",
    "terms_conditions": "Terms and conditions",
    "about_the_shop": "About the shop",
    "who_we_are": "Who we are",
    "contacts": "Contacts",
    "books_sustainability": "Books sustainability",
    "for_customers": "For customers",
    "loyalty_programme": "Loyalty programme",
    "order_status": "Order status",
    "returns_complaints": "Returns / Complaints",
    "lets_stay_together": "Let's stay together",
    
    // HeroSection
    "buy_book": "Buy book",
    "video_btn": "Video",
    
    // FeaturesBar
    "23_million_titles": "23 million titles",
    "in_150_languages": "in 150+ languages",
    "great_prices": "Great prices",
    "always_up_to_date": "always up-to-date",
    "libroamanto_club": "LIBROAMANTO club",
    "full_of_gifts": "full of gifts",
    "2_million_customers": "2 million customers",
    "served_every_year": "served every year",
    
    // Categories
    "explore_categories": "Explore Categories",
    "classic_modern_print": "Classic and Modern Print",
    "digital_reading_exp": "Digital Reading Experience",
    "listen_to_stories": "Listen to Your Stories",
    "gifts_category": "Gifts",
    "special_items_lovers": "Special Items for Lovers",
    "view_collection": "View Collection",

    // Home sections
    "new_arrivals": "New Arrivals",
    "freshly_added": "Freshly added to our collection",
    "bestsellers": "Bestsellers",
    "most_loved_books": "Most loved books by our readers",
    "book_set_of_month": "BOOK SET OF THE MONTH",
    "carefully_selected": "Carefully selected books for this month",
    "award_winning_books": "AWARD-WINNING BOOKS",
    "critically_acclaimed": "Critically acclaimed and celebrated literature",
    "world_literature": "World Literature",
    "timeless_classics": "Timeless classics from around the globe",
    "only": "Only",
    "left": "left!",
    "unknown_author": "Unknown Author",

    // PromoBanner
    "join_the": "Join the",
    "club": "Club",
    "promo_desc": "Get exclusive discounts, early access to new releases, and free shipping on your first order!",
    "enter_email": "Enter your email address",
    "join_now": "Join Now",
    "promo_terms": "By joining, you agree to our Terms & Conditions and Privacy Policy",

    // AI Widget
    "ai_greeting": "Hi there! 📚 I'm blendartbook AI, your personal book assistant. I can help you discover amazing books, recommend reads based on your taste, or answer any questions about our library. What are you looking for today?",
    "recommend_book": "📖 Recommend a book",
    "popular_genres": "🎭 Popular genres",
    "gift_ideas": "🎁 Gift ideas",
    "ask_me_about": "Ask me about books...",
    "powered_by": "Powered by blendartbook AI ✨",
    // Listing pages
    "properties": "Properties",
    "price_up_to": "Price: up to €",
    "items_found": "items found",
    "sort_by_popularity": "Sort by: Popularity",
    "no_products_found": "No products found.",
    "english": "English",
    "turkish": "Turkish",
    "romanian": "Romanian",
    "bulgarian": "Bulgarian",
    "all": "All",
    "audio_filters": "Audio Filters",
    "max_price": "Max Price: €",
    "audio_library": "Audio Library:",
    "syncing": "Syncing...",
    "tuning_frequencies": "Tuning frequencies...",
    "no_audiobooks_found": "No audiobooks found matching your criteria.",
    "browsing": "Browsing:",
    "no_products_collection": "No products found in this collection.",
    "error_label": "Error:",
    "all_products": "All Products",
    // Auth
    "set_new_password": "Set your new password",
    "reset_your_password": "Reset your password",
    "welcome_back": "Welcome back",
    "create_an_account": "Create an Account",
    "choose_secure_password": "Choose a secure password and save it.",
    "email_reset_link": "We'll email you a password reset link.",
    "enter_details_access": "Enter your details to access your account.",
    "join_track_orders": "Join us to track orders and save your cart.",
    "check_your_email": "Check your email!",
    "if_account_exists": "If an account exists for",
    "receive_reset_link": "you'll receive a reset link shortly.",
    "return_to_login": "Return to Login",
    "sent_confirmation_link": "We've sent a confirmation link to",
    "click_verify_account": "Please click it to verify your account.",
    "full_name": "Full Name",
    "phone_number": "Phone Number",
    "email_address": "Email Address",
    "password_label": "Password",
    "forgot_password": "Forgot password?",
    "at_least_6_chars": "At least 6 characters",
    "new_password": "New Password",
    "confirm_password": "Confirm Password",
    "repeat_new_password": "Repeat new password",
    "update_password": "Update Password",
    "send_reset_link": "Send Reset Link",
    "log_in": "Log In",
    "create_account_btn": "Create Account",
    "back_to_login": "Back to Login",
    "dont_have_account": "Don't have an account?",
    "already_have_account": "Already have an account?",
    "sign_up_free": "Sign up for free",
    "log_in_here": "Log in here",

    // Account
    "my_account": "My Account",
    "profile_details": "Profile Details",
    "my_orders": "My Orders",
    "log_out": "Log Out",
    "shipping_contact_details": "Shipping & Contact Details",
    "profile_updated_success": "Profile updated successfully!",
    "delivery_address": "Delivery Address",
    "saving": "Saving...",
    "save_changes": "Save Changes",
    "no_orders_yet": "You haven't placed any orders yet.",
    "delivered": "Delivered",
    "in_transit": "In Transit",
    "order_items": "Order Items",
    "qty": "Qty:",
    "total": "Total:",
    "status": "Status:",
    "john_doe": "John Doe",

    // Update Password
    "set_new_password_title": "Set a new password",
    "enter_new_password_desc": "Enter a new password for your account.",
    "missing_expired_link": "This reset link is missing or expired. Please go back and request a new password reset email.",
    "go_to_signin": "Go to Sign In",
    "password_updated": "Password updated",
    "can_signin_new_password": "You can now sign in with your new password.",
    "continue_to_signin": "Continue to Sign In",
    "repeat_password": "Repeat password",
    "payment_successful": "Payment successful",
    "payment_received_desc": "Thank you. Your payment has been received and processed securely.",
    "order_number": "Order Number",
    "estimated_delivery": "Your order will reach you in 5-6 days.",
    "continue_shopping": "Continue shopping",
    "back_to_cart": "Back to Cart",
      "shopping_hero_desc": "Everything you need to know about your shopping experience at BlendArtBook. We strive to make it seamless, secure, and inspiring.",
    "easy_ordering": "Easy Ordering",
    "easy_ordering_desc": "Add your favorite books or art pieces to your cart with one click. Our checkout process is optimized for speed and clarity.",
    "secure_payments": "Secure Payments",
    "secure_payments_desc": "We use industry-leading encryption (SSL) and trusted payment gateways like Stripe and Revolut to ensure your data is always safe.",
    "fast_processing": "Fast Processing",
    "fast_processing_desc": "Orders are processed within 24 hours. You will receive a tracking number as soon as your package leaves our warehouse.",
    "cust_support_desc": "Our support team is available via chat and email to help you with any questions about your order or our products.",
    "how_to_shop": "How to shop?",
    "how_to_shop_desc": "Browsing through our collection is easy. You can use the search bar to find specific titles or explore our curated categories from the main menu.",
    "tracking_order": "Tracking your order",
    "tracking_order_desc": "After placing an order, you can view its status in your account dashboard. We also send automated email updates at every stage.",
    "need_help_order": "Need help with your order?",
    "support_experts_desc": "Our support experts are ready to assist you with any questions about products, shipping, or returns.",
    "contact_support": "Contact Support",
    "shipping_info": "Shipping Info",
    "standard_delivery": "Standard Delivery",
    "free_shipping_over": "Free Shipping on orders over €30",
    "payment_methods_title": "Payment Methods",
    "instant_confirmation": "Instant Confirmation",
    "mission_title": "Our Mission",
    "mission_desc": "To democratize access to rare art books and unique handmade items, fostering a world where creativity knows no borders.",
    "email_us": "Email Us",
    "call_us": "Call Us",
    "visit_us": "Visit Us",
    "live_chat": "Live Chat",
    "terms_hero_desc": "Our commitment to transparency, fairness, and the protection of your rights.",
    "terms_section1_title": "1. Acceptance of Terms",
    "terms_section1_content": "By accessing and using BlendArtBook, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. If you do not agree, please refrain from using our services.",
    "terms_section2_title": "2. Privacy & Data",
    "terms_section2_content": "Your privacy is paramount. We handle all personal data in accordance with our Privacy Policy and relevant international regulations (GDPR, etc.). We never sell your data to third parties.",
    "terms_section3_title": "3. Intellectual Property",
    "terms_section3_content": "All content on this site, including text, graphics, logos, and images, is the property of BlendArtBook or its content suppliers and is protected by international copyright laws.",
    "terms_questions_title": "Questions about our terms?",
    "terms_questions_desc": "If you need clarification on any of our policies, our team is happy to provide more detailed information.",
    "who_we_are_hero_title": "Crafting stories, inspiring minds.",
    "who_we_are_hero_desc": "BlendArtBook was born out of a simple passion: to bring the world's most beautiful books and art pieces to a global community of curious readers and art lovers.",
    "curated_with_love": "Curated with Love",
    "quality_first": "Quality First",
    "contacts_hero_desc": "We're here to help. Reach out to us through any of these channels.",
    "live_chat_desc": "Need immediate assistance? Our AI assistant and support team are available 24/7.",
    "start_conversation": "Start a Conversation",
    "sustainability_desc": "Our commitment to the planet and responsible publishing.",
    "sustainability_content": "We believe in a sustainable future for the world of art and literature. We source our paper from FSC-certified forests and use eco-friendly inks whenever possible.",
    "loyalty_desc": "Rewarding our most passionate readers and collectors.",
    "loyalty_content": "Join the BlendArtBook Loyalty Programme to earn points on every purchase. Points can be redeemed for exclusive discounts and free shipping.",
    "returns_desc": "Hassle-free returns and dedicated support for your satisfaction.",
    "returns_content": "Not satisfied with your purchase? No problem. We offer a 30-day return policy for all items in their original condition.",
    "still_have_questions": "Still have questions?",
    "support_team_desc": "Our dedicated support team is ready to assist you with any further details regarding this topic.",
    "cookies": "Cookies",
    "privacy": "Privacy",
    "accessibility": "Accessibility",
    "delivery_hero_desc": "Reliable shipping and secure payment methods for your peace of mind.",
    "standard_delivery_desc": "3-5 business days across Europe.",
    "worldwide_shipping": "Worldwide Shipping",
    "credit_debit_cards": "Credit/Debit Cards",
    "revolut_pay": "Revolut Pay",
    "art_street_address": "123 Art Street, London, UK",
    "shopping_cart": "Shopping Cart",
    "order_summary": "Order Summary",
    "product_label": "Product",
    "number_label": "Number",
    "stock_availability": "Stock Availability",
    "gift_wrapping": "Gift-wrapping",
    "price_label": "Price",
    "cart_empty": "Your cart is empty.",
    "in_stock": "In stock",
    "shipping_24h": "Shipping within 24 hours",
    "select_option": "Select",
    "gift_wrap_yes": "Yes (+2.00 €)",
    "have_coupon": "Do you have a discount coupon?",
    "coupon_placeholder": "Code...",
    "apply_btn": "Apply",
    "remove_btn": "Remove",
    "example_codes": "Example codes:",
    "subtotal_label": "Subtotal:",
    "total_price_label": "Total price:",
    "back_to_shop": "Back to the shop",
    "proceed_to_checkout": "Proceed to delivery & payment",
    "discount_label": "discount",
    "book_label": "Book",
    "secure_checkout": "Secure Checkout",
    "delivery_payment_title": "Delivery & Payment",
    "back_to_cart": "Back to cart",
    "payment_method": "Payment method",
    "promo_voucher_optional": "Promo code / voucher (optional)",
    "promo_empty_continue": "No code? Leave this empty and continue.",
    "save_card_future": "Save this card for future payments",
    "i_accept": "I accept",
    "distance_sales_agreement": "Distance Sales Agreement",
    "refund_cancellation": "Refund & Cancellation",
    "and_conjunction": "and",
    "kvkk_notice": "KVKK Privacy Notice",
    "redirecting_revolut": "Redirecting to Revolut...",
    "pay_with_revolut": "Pay with Revolut",
    "revolut_instruction": "Revolut hosted checkout page for real card payments and wallet methods.",
    "preparing_payment": "Preparing secure payment...",
    "open_card_form": "Open card details form",
    "card_form_click_instruction": "Click “Open card details form” to enter card number, expiry date, and CVV.",
    "saved_cards_email": "Saved cards for this email",
    "refresh_btn": "Refresh",
    "no_saved_cards": "No saved cards yet.",
    "loading_cards": "Loading cards...",
    "no_items_cart": "No items in cart yet.",
    "order_save_error": "Order could not be saved. Please try again.",
    "payment_failed": "Payment failed. Please try again.",
    "processing_payment": "Processing payment...",
    "pay_now": "Pay now",
    "card_form_instruction": "Secure payment powered by Stripe.",
    "saving_order": "Saving order...",
    "continue_pod": "Continue with Pay on delivery",
    "stripe_not_configured": "Online card payment is not configured yet. Add NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY and STRIPE_SECRET_KEY to enable it.",
    "payment_successful": "Payment successful!",
    "payment_received_desc": "Your order has been received and is being processed. You will receive an email confirmation shortly.",
    "estimated_delivery": "Estimated delivery: 2-5 business days.",
    "items_count_label": "items",
    "confirmation_sent_to": "Confirmation sent to",
    "preparing_order_summary": "Preparing order summary...",
    "order_details_not_found": "Order details could not be found.",
    "go_back_home": "Go back to home",
    "continue_shopping": "Continue shopping",
    "order_number_label": "Order number",
    "qty_label": "Qty",
    "author_label": "Author",
    "publisher_label": "Publisher",
    "add_to_library": "Add to library",
    "in_basket": "In basket",
    "all_formats": "All formats",
    "paperback": "Paperback",
    "estimated_shipping": "Estimated shipping date",
    "free_shipping_promo": "Free shipping over €30",
    "featured_info": "Featured Information",
    "paper_type": "Paper Type",
    "page_count": "Page Count",
    "dimensions": "Dimensions",
    "first_edition_year": "First Edition Year",
    "edition_number": "Edition Number",
    "see_all_features": "See all features",
    "add_to_cart": "Add to cart",
    "out_of_stock": "Out of stock",
    "added": "Added!",
    "back_to_shop": "Back to shop",
    "product_description_tab": "Product Description",
    "reviews_tab": "Reviews",
    "returns_tab": "Returns & Cancellations",
    "reviews_count": "Reviews",
    "show_more_reviews": "Show More Reviews",
    "no_reviews_yet": "No reviews for this product yet.",
    "cancellation_faq_1": "How can I cancel my order?",
    "cancellation_faq_2": "How can I return the product I received?",
    "cancellation_faq_3": "Can I cancel one or more items in my order?",
    "cancellation_faq_4": "Can I cancel a wire transfer order that hasn't been approved yet?",
    "cancellation_faq_5": "Can I reactivate my cancelled gift card?",
    "cancellation_faq_6": "If I used a gift card in my cancelled order, will the amount be refunded?",
    "cancellation_faq_7": "What can I do if the product(s) I requested to cancel have been shipped?",
    "cancellation_ans_1": "You can cancel your order from the 'My Orders' section before it is shipped. If it has been shipped, you can return it after receiving it.",
    "cancellation_ans_2": "You can return products within 14 days of receipt. Simply create a return request and send it back with the provided shipping code.",
    "cancellation_ans_3": "Yes, you can select specific items to cancel as long as they haven't been prepared for shipping yet.",
    "cancellation_ans_4": "Yes, transfer orders can be cancelled easily through the order management screen before the payment is processed.",
    "cancellation_ans_5": "Gift cards used in cancelled orders are usually reactivated automatically or a new code is sent to your email.",
    "cancellation_ans_6": "Yes, the amount spent from your gift card will be refunded back to the card balance or as a new discount code.",
    "cancellation_ans_7": "If the shipping process has started, the cancellation cannot be completed. You should refuse the delivery or return it after receipt.",
    "default_description": "A detailed description of this book will be added soon.",
    "from_promo_bulletin": "(From the Promotional Bulletin)",
    "paper_type_default": "Quality Paper",
    "edition_default": "First Edition",
    "turkish": "Turkish",
    "book_name_label": "Book Name",
    "review_1_comment": "Excellent book!",
    "review_2_comment": "So beautiful, it even came with a bookmark. I highly recommend it.",
    "review_3_comment": "We read it with my son with great joy and laughter. It contributes to children's vocabulary development.",
    "write_review": "Write a Review",
    "your_name": "Your Name",
    "your_rating": "Your Rating",
    "your_comment": "Your Comment",
    "submit_review": "Submit Review",
    "review_submitted_msg": "Thank you! Your review has been submitted for approval.",
    "cancel_btn": "Cancel",
    "lang_code": "en-US",
    "product_not_found": "Product Not Found",
    "product_not_found_desc": "The product you are looking for may have been removed or moved.",
    "go_back": "Go Back",
    "language": "Language",
},

  bg: {
    "check_order_status": "Проверете статуса на поръчката",
    "free_delivery": "Безплатна доставка над €30",
    
    "search_placeholder": "Търсете книги, автори, категории...",
    "search": "Търсене",
    
    "books": "Книги",
    "art": "Изкуство",
    "handmade": "Ръчна изработка",
    "ebooks": "Е-книги",
    "audiobooks": "Аудиокниги",
    "other_products": "Други продукти",
    "gift_tips": "Идеи за подаръци",
    "gift_voucher": "Подаръчен ваучер",
    "cart": "Кошница",
    
    "hi": "Здравей",
    
    "books_title": "16 386 577 книги на 175 езика",
    "ebooks_title": "1 245 000 е-книги за изтегляне",
    "audiobooks_title": "450 000 аудиокниги за вашите уши",
    "art_title": "Открийте уникални произведения на изкуството",
    "help_text": "Не знаете какво да изберете? Ние сме тук, за да помогнем!",
    "buy_now": "Купи сега",

    "books_in_english": "Книги на английски",
    "books_in_turkish": "Книги на турски",
    "books_in_romanian": "Книги на румънски",
    "books_in_bulgarian": "Книги на български",

    "ebooks_in_turkish": "Е-книги на турски",
    "ebooks_in_english": "Е-книги на английски",
    "ebooks_in_romanian": "Е-книги на румънски",
    "ebooks_in_bulgarian": "Е-книги на български",

    "audiobooks_in_turkish": "Аудиокниги на турски",
    "audiobooks_in_english": "Аудиокниги на английски",
    "audiobooks_in_romanian": "Аудиокниги на румънски",
    "audiobooks_in_bulgarian": "Аудиокниги на български",

    "calendar_diary": "Календар/Дневник",
    "audio": "Аудио",
    "game_toy": "Игра/Играчка",
    "video": "Видео",
    "printed_items": "Печатни материали",
    "stationery": "Канцеларски материали",
    "digital": "Дигитални",

    "gifts_for_women": "Подаръци за жени",
    "gifts_for_men": "Подаръци за мъже",
    "gifts_for_girls": "Подаръци за момичета",
    "gifts_for_boys": "Подаръци за момчета",
    "gifts_for_children": "Подаръци за деца",

    "painting": "Живопис",
    "sculpture": "Скулптура",
    "music": "Музика",
    "crafts": "Занаяти",

    "be_whoever": "Бъди Който Пожелаеш",
    "worlds_widest_selection": "НАЙ-ГОЛЕМИЯТ ИЗБОР НА КНИГИ В СВЕТА",
    "all_the_books": "Всички книги на света",
    "all_about_shopping": "Всичко за пазаруването",
    "delivery_payment": "Доставка и плащане",
    "terms_conditions": "Условия за ползване",
    "about_the_shop": "За магазина",
    "who_we_are": "Кои сме ние",
    "contacts": "Контакти",
    "books_sustainability": "Устойчивост на книгите",
    "for_customers": "За клиенти",
    "loyalty_programme": "Програма за лоялност",
    "order_status": "Статус на поръчката",
    "returns_complaints": "Връщане / Оплаквания",
    "lets_stay_together": "Нека останем заедно",
    
    "buy_book": "Купи книга",
    "video_btn": "Видео",
    
    "23_million_titles": "23 милиона заглавия",
    "in_150_languages": "на 150+ езика",
    "great_prices": "Страхотни цени",
    "always_up_to_date": "винаги актуални",
    "libroamanto_club": "Клуб LIBROAMANTO",
    "full_of_gifts": "пълен с подаръци",
    "2_million_customers": "2 милиона клиенти",
    "served_every_year": "обслужвани всяка година",
    
    "explore_categories": "Разгледайте категориите",
    "classic_modern_print": "Класически и модерен печат",
    "digital_reading_exp": "Дигитално четене",
    "listen_to_stories": "Слушайте историите си",
    "gifts_category": "Подаръци",
    "special_items_lovers": "Специални артикули за влюбени",
    "view_collection": "Вижте колекцията",

    "new_arrivals": "Нови предложения",
    "freshly_added": "Току-що добавени към нашата колекция",
    "bestsellers": "Бестселъри",
    "most_loved_books": "Най-обичаните книги от нашите читатели",
    "book_set_of_month": "КНИЖЕН КОМПЛЕКТ НА МЕСЕЦА",
    "carefully_selected": "Внимателно подбрани книги за този месец",
    "award_winning_books": "НАГРАЖДАВАНИ КНИГИ",
    "critically_acclaimed": "Критично призната и прочута литература",
    "world_literature": "Световна литература",
    "timeless_classics": "Вечни класики от цял свят",
    "only": "Само",
    "left": "останали!",
    "unknown_author": "Неизвестен автор",

    "join_the": "Присъединете се към",
    "club": "клуб",
    "promo_desc": "Получете ексклузивни отстъпки, ранен достъп до нови издания и безплатна доставка за първата си поръчка!",
    "enter_email": "Въведете вашия имейл адрес",
    "join_now": "Присъедини се сега",
    "promo_terms": "С присъединяването си се съгласявате с нашите Условия за ползване и Политика за поверителност",

    "ai_greeting": "Здравейте! 📚 Аз съм AI на blendartbook, вашият личен асистент за книги. Мога да ви помогна да откриете невероятни книги, да препоръчам четива въз основа на вашия вкус или да отговоря на всякакви въпроси относно нашата библиотека. Какво търсите днес?",
    "recommend_book": "📖 Препоръчай книга",
    "popular_genres": "🎭 Популярни жанрове",
    "gift_ideas": "🎁 Идеи за подаръци",
    "ask_me_about": "Попитайте ме за книги...",
    "powered_by": "Задвижвано от blendartbook AI ✨",
    "properties": "Свойства",
    "price_up_to": "Цена: до €",
    "items_found": "намерени продукта",
    "sort_by_popularity": "Сортиране по: Популярност",
    "no_products_found": "Няма намерени продукти.",
    "english": "Английски",
    "turkish": "Турски",
    "romanian": "Румънски",
    "bulgarian": "Български",
    "all": "Всички",
    "audio_filters": "Аудио филтри",
    "max_price": "Макс. цена: €",
    "audio_library": "Аудио библиотека:",
    "syncing": "Синхронизиране...",
    "tuning_frequencies": "Настройване на честотите...",
    "no_audiobooks_found": "Няма намерени аудиокниги, отговарящи на вашите критерии.",
    "browsing": "Разглеждане:",
    "no_products_collection": "Няма намерени продукти в тази колекция.",
    "error_label": "Грешка:",
    "all_products": "Всички продукти",
    "set_new_password": "Задайте нова парола",
    "reset_your_password": "Възстановете паролата си",
    "welcome_back": "Добре дошли отново",
    "create_an_account": "Създайте профил",
    "choose_secure_password": "Изберете сигурна парола и я запазете.",
    "email_reset_link": "Ще ви изпратим линк за възстановяване на паролата.",
    "enter_details_access": "Въведете данните си за достъп.",
    "join_track_orders": "Присъединете се, за да следите поръчките си.",
    "check_your_email": "Проверете имейла си!",
    "if_account_exists": "Ако съществува профил за",
    "receive_reset_link": "ще получите линк скоро.",
    "return_to_login": "Към Вход",
    "sent_confirmation_link": "Изпратихме линк за потвърждение на",
    "click_verify_account": "Кликнете върху него, за да потвърдите профила си.",
    "full_name": "Пълно име",
    "phone_number": "Телефон",
    "email_address": "Имейл адрес",
    "password_label": "Парола",
    "forgot_password": "Забравена парола?",
    "at_least_6_chars": "Поне 6 символа",
    "new_password": "Нова парола",
    "confirm_password": "Потвърдете паролата",
    "repeat_new_password": "Повторете новата парола",
    "update_password": "Обнови паролата",
    "send_reset_link": "Изпрати линк",
    "log_in": "Вход",
    "create_account_btn": "Създай профил",
    "back_to_login": "Назад към Вход",
    "dont_have_account": "Нямате профил?",
    "already_have_account": "Вече имате профил?",
    "sign_up_free": "Регистрирай се безплатно",
    "log_in_here": "Влез тук",

    "my_account": "Моят профил",
    "profile_details": "Данни на профила",
    "my_orders": "Моите поръчки",
    "log_out": "Изход",
    "shipping_contact_details": "Данни за доставка",
    "profile_updated_success": "Профилът е обновен успешно!",
    "delivery_address": "Адрес за доставка",
    "saving": "Запазване...",
    "save_changes": "Запази промените",
    "no_orders_yet": "Все още нямате поръчки.",
    "delivered": "Доставена",
    "in_transit": "В транзит",
    "order_items": "Артикули",
    "qty": "Количество:",
    "total": "Общо:",
    "status": "Статус:",
    "john_doe": "Иван Иванов",

    "set_new_password_title": "Задайте нова парола",
    "enter_new_password_desc": "Въведете нова парола за профила си.",
    "missing_expired_link": "Този линк е невалиден или с изтекъл срок.",
    "go_to_signin": "Към Вход",
    "password_updated": "Паролата е обновена",
    "can_signin_new_password": "Вече можете да влезете с новата си парола.",
    "continue_to_signin": "Продължи към Вход",
    "repeat_password": "Повторете паролата",
    "payment_successful": "Плащането е успешно",
    "payment_received_desc": "Благодарим ви. Вашето плащане е получено и обработено сигурно.",
    "order_number": "Номер на поръчка",
    "estimated_delivery": "Вашата поръчка ще пристигне при вас след 5-6 дни.",
    "continue_shopping": "Продължете с пазаруването",
    "back_to_cart": "Назад към количката",
      "shopping_hero_desc": "Всичко, което трябва да знаете за вашето пазаруване в BlendArtBook. Стремим се да го направим безпроблемно, безопасно и вдъхновяващо.",
    "easy_ordering": "Лесна поръчка",
    "easy_ordering_desc": "Добавете любимите си книги или предмети на изкуството в количката си с едно кликване. Процесът ни е оптимизиран за скорост и яснота.",
    "secure_payments": "Сигурни плащания",
    "secure_payments_desc": "Използваме водещо в индустрията криптиране (SSL) и доверени платежни портали като Stripe и Revolut за сигурност на вашите данни.",
    "fast_processing": "Бърза обработка",
    "fast_processing_desc": "Поръчките се обработват в рамките на 24 часа. Ще получите номер за проследяване веднага щом пакетът напусне склада ни.",
    "cust_support_desc": "Нашият екип за поддръжка е на разположение чрез чат и имейл, за да ви помогне с всякакви въпроси относно вашата поръчка.",
    "how_to_shop": "Как да пазаруваме?",
    "how_to_shop_desc": "Разглеждането на нашата колекция е лесно. Можете да използвате лентата за търсене или да разгледате нашите категории.",
    "tracking_order": "Проследяване на поръчка",
    "tracking_order_desc": "След като направите поръчка, можете да видите нейния статус в таблото на вашия акаунт. Изпращаме и автоматични актуализации по имейл.",
    "need_help_order": "Нуждаете се от помощ за вашата поръчка?",
    "support_experts_desc": "Нашите експерти по поддръжка са готови да ви съдействат с всякакви въпроси относно продукти, доставка или връщане.",
    "contact_support": "Свържете се с поддръжката",
    "shipping_info": "Информация за доставка",
    "standard_delivery": "Стандартна доставка",
    "free_shipping_over": "Безплатна доставка за поръчки над 30 €",
    "payment_methods_title": "Методи за плащане",
    "instant_confirmation": "Незабавно потвърждение",
    "mission_title": "Нашата мисия",
    "mission_desc": "Да демократизираме достъпа до редки арт книги и уникални ръчно изработени предмети, създавайки свят без граници за творчеството.",
    "email_us": "Изпратете ни имейл",
    "call_us": "Обадете ни се",
    "visit_us": "Посетете ни",
    "live_chat": "Чат на живо",
    "terms_hero_desc": "Нашият ангажимент за прозрачност, справедливост и защита на вашите права.",
    "terms_section1_title": "1. Приемане на условията",
    "terms_section1_content": "Чрез достъпа до и използването на BlendArtBook вие потвърждавате, че сте прочели, разбрали и се съгласявате да бъдете обвързани с тези Общи условия. Ако не сте съгласни, моля, въздържайте се от използване на нашите услуги.",
    "terms_section2_title": "2. Поверителност и данни",
    "terms_section2_content": "Вашата поверителност е от първостепенно значение. Ние обработваме всички лични данни в съответствие с нашата Политика за поверителност и съответните международни разпоредби (GDPR и др.). Никога не продаваме вашите данни на трети страни.",
    "terms_section3_title": "3. Интелектуална собственост",
    "terms_section3_content": "Цялото съдържание на този сайт, включително текст, графики, лога и изображения, е собственост на BlendArtBook или неговите доставчици на съдържание и е защитено от международните закони за авторското право.",
    "terms_questions_title": "Въпроси относно нашите условия?",
    "terms_questions_desc": "Ако имате нужда от разяснение относно някоя от нашите политики, нашият екип ще се радва да предостави по-подробна информация.",
    "who_we_are_hero_title": "Създаваме истории, вдъхновяваме умове.",
    "who_we_are_hero_desc": "BlendArtBook се роди от проста страст: да пренесе най-красивите книги и предмети на изкуството в света до глобална общност от любопитни читатели и любители на изкуството.",
    "curated_with_love": "Подбрано с любов",
    "quality_first": "Качеството на първо място",
    "contacts_hero_desc": "Тук сме, за да помогнем. Свържете се с нас чрез някой от тези канали.",
    "live_chat_desc": "Нуждаете се от незабавна помощ? Нашият AI асистент и екип за поддръжка са на разположение 24/7.",
    "start_conversation": "Започнете разговор",
    "sustainability_desc": "Нашият ангажимент към планетата и отговорното публикуване.",
    "sustainability_content": "Вярваме в устойчивото бъдеще за света на изкуството и литературата. Снабдяваме се с хартия от FSC-сертифицирани гори и използваме екологични мастила.",
    "loyalty_desc": "Възнаграждаваме нашите най-страстни читатели и колекционери.",
    "loyalty_content": "Присъединете се към програмата за лоялност на BlendArtBook, за да печелите точки при всяка покупка. Точките могат да се обменят за ексклузивни отстъпки и безплатна доставка.",
    "returns_desc": "Безпроблемно връщане и специална поддръжка за вашето удовлетворение.",
    "returns_content": "Не сте доволни от покупката си? Няма проблем. Предлагаме 30-дневна политика за връщане на всички артикули в оригиналното им състояние.",
    "still_have_questions": "Все още имате въпроси?",
    "support_team_desc": "Нашият специализиран екип за поддръжка е готов да ви съдейства с всякакви допълнителни подробности по тази тема.",
    "cookies": "Бисквитки",
    "privacy": "Поверителност",
    "accessibility": "Достъпност",
    "delivery_hero_desc": "Надеждна доставка и сигурни методи за плащане за вашето спокойствие.",
    "standard_delivery_desc": "3-5 работни дни в цяла Европа.",
    "worldwide_shipping": "Доставка в целия свят",
    "credit_debit_cards": "Кредитни/Дебитни карти",
    "revolut_pay": "Плащане с Revolut",
    "art_street_address": "ул. Изкуство 123, Лондон, Обединено кралство",
    "shopping_cart": "Кошница",
    "order_summary": "Обобщение на поръчката",
    "product_label": "Продукт",
    "number_label": "Брой",
    "stock_availability": "Наличност",
    "gift_wrapping": "Опаковка за подарък",
    "price_label": "Цена",
    "cart_empty": "Кошницата ви е празна.",
    "in_stock": "В наличност",
    "shipping_24h": "Изпращане до 24 часа",
    "select_option": "Избор",
    "gift_wrap_yes": "Да (+2.00 €)",
    "have_coupon": "Имате ли купон за отстъпка?",
    "coupon_placeholder": "Код...",
    "apply_btn": "Приложи",
    "remove_btn": "Премахни",
    "example_codes": "Примерни кодове:",
    "subtotal_label": "Междинна сума:",
    "total_price_label": "Обща цена:",
    "back_to_shop": "Назад към магазина",
    "proceed_to_checkout": "Продължете към доставка и плащане",
    "discount_label": "отстъпка",
    "book_label": "Книга",
    "secure_checkout": "Сигурно плащане",
    "delivery_payment_title": "Доставка и плащане",
    "back_to_cart": "Назад към количката",
    "payment_method": "Метод за плащане",
    "promo_voucher_optional": "Промо код / ваучер (по избор)",
    "promo_empty_continue": "Нямате код? Оставете празно и продължете.",
    "save_card_future": "Запази тази карта за бъдещи плащания",
    "i_accept": "Приемам",
    "distance_sales_agreement": "Договор за продажба от разстояние",
    "refund_cancellation": "Политика за връщане и анулиране",
    "and_conjunction": "и",
    "kvkk_notice": "Уведомление за поверителност",
    "redirecting_revolut": "Пренасочване към Revolut...",
    "pay_with_revolut": "Плати с Revolut",
    "revolut_instruction": "Страница за плащане на Revolut за реални картови плащания и методи на портфейла.",
    "preparing_payment": "Подготовка на сигурно плащане...",
    "open_card_form": "Отвори формата за данни на картата",
    "card_form_click_instruction": "Кликнете „Отвори формата за данни на картата“, за да въведете номер на карта, срок на валидност и CVV.",
    "saved_cards_email": "Запазени карти за този имейл",
    "refresh_btn": "Обнови",
    "no_saved_cards": "Все още няма запазени карти.",
    "loading_cards": "Зареждане на карти...",
    "no_items_cart": "Все още няма продукти в количката.",
    "order_save_error": "Поръчката не можа да бъде запазена. Моля, опитайте отново.",
    "payment_failed": "Плащането не бе успешно. Моля, опитайте отново.",
    "processing_payment": "Обработка на плащането...",
    "pay_now": "Плати сега",
    "card_form_instruction": "Сигурно плащане чрез Stripe.",
    "saving_order": "Запазване на поръчката...",
    "continue_pod": "Продължете с плащане при доставка",
    "stripe_not_configured": "Онлайн плащането с карта още не е конфигурирано. Добавете ключовете, за да го активирате.",
    "payment_successful": "Плащането е успешно!",
    "payment_received_desc": "Поръчката Ви е получена и се обработва. Скоро ще получите потвърждение по имейл.",
    "estimated_delivery": "Очаквана доставка: 2-5 работни дни.",
    "items_count_label": "артикула",
    "confirmation_sent_to": "Потвърждението е изпратено на",
    "preparing_order_summary": "Подготовка на резюме на поръчката...",
    "order_details_not_found": "Детайлите на поръчката не бяха намерени.",
    "go_back_home": "Върнете се в началото",
    "continue_shopping": "Продължете с пазаруването",
    "order_number_label": "Номер на поръчка",
    "qty_label": "Количество",
    "author_label": "Автор",
    "publisher_label": "Издателство",
    "add_to_library": "Добави в библиотеката",
    "in_basket": "В количката",
    "all_formats": "Всички формати",
    "paperback": "Меки корици",
    "estimated_shipping": "Очаквана дата на доставка",
    "free_shipping_promo": "Безплатна доставка над €30",
    "featured_info": "Представена информация",
    "paper_type": "Тип хартия",
    "page_count": "Брой страници",
    "dimensions": "Размери",
    "first_edition_year": "Година на първо издание",
    "edition_number": "Номер на изданието",
    "see_all_features": "Виж всички функции",
    "add_to_cart": "Добави в количката",
    "out_of_stock": "Изчерпано",
    "added": "Добавено!",
    "back_to_shop": "Обратно в магазина",
    "product_description_tab": "Описание на продукта",
    "reviews_tab": "Отзиви",
    "returns_tab": "Връщане и анулиране",
    "reviews_count": "Отзиви",
    "show_more_reviews": "Покажи повече отзиви",
    "no_reviews_yet": "Все още няма отзиви за този продукт.",
    "cancellation_faq_1": "Как мога да анулирам поръчката си?",
    "cancellation_faq_2": "Как мога да върна продукта, който получих?",
    "cancellation_faq_3": "Мога ли да анулирам един или повече артикула от поръчката си?",
    "cancellation_faq_4": "Мога ли да анулирам поръчка с банков превод, която още не е одобрена?",
    "cancellation_faq_5": "Мога ли да активирам отново анулираната си карта за подарък?",
    "cancellation_faq_6": "Ако съм използвал карта за подарък в анулираната си поръчка, сумата ще бъде ли възстановена?",
    "cancellation_faq_7": "Какво мога да направя, ако продуктите, които поисках да анулирам, вече са изпратени?",
    "cancellation_ans_1": "Можете да анулирате поръчката си от секция 'Моите поръчки' преди да бъде изпратена. Ако вече е изпратена, можете да я върнете след като я получите.",
    "cancellation_ans_2": "Можете да върнете продукти в рамките на 14 дни след получаването им. Просто създайте заявка за връщане и ги изпратете обратно с предоставения код за доставка.",
    "cancellation_ans_3": "Да, можете да изберете конкретни артикули за анулиране, стига те все още да не са подготвени за изпращане.",
    "cancellation_ans_4": "Да, поръчките с банков превод могат лесно да бъдат анулирани чрез екрана за управление на поръчки, преди плащането да бъде обработено.",
    "cancellation_ans_5": "Картите за подарък, използвани в анулирани поръчки, обикновено се активират автоматично или на вашия имейл се изпраща нов код.",
    "cancellation_ans_6": "Да, сумата, похарчена от вашата карта за подарък, ще бъде възстановена обратно в баланса на картата или като нов код за отстъпка.",
    "cancellation_ans_7": "Ако процесът на доставка е започнал, анулирането не може да бъде завършено. Трябва да откажете доставката или да я върнете след получаване.",
    "default_description": "Скоро ще бъде добавено подробно описание на тази книга.",
    "from_promo_bulletin": "(От промоционалния бюлетин)",
    "paper_type_default": "Качествена хартия",
    "edition_default": "Първо издание",
    "turkish": "Турски",
    "book_name_label": "Име на книгата",
    "review_1_comment": "Отлична книга!",
    "review_2_comment": "Толкова красива, дори дойде с разделител за книги. Силно я препоръчвам.",
    "review_3_comment": "Четем я със сина ми с голяма радост и смях. Допринася за развитието на речника на децата.",
    "write_review": "Напишете отзив",
    "your_name": "Вашето име",
    "your_rating": "Вашата оценка",
    "your_comment": "Вашият коментар",
    "submit_review": "Изпрати отзив",
    "review_submitted_msg": "Благодарим ви! Вашият отзив е изпратен за одобрение.",
    "cancel_btn": "Отказ",
    "lang_code": "bg-BG",
    "product_not_found": "Продуктът не е намерен",
    "product_not_found_desc": "Продуктът, който търсите, може да е бил премахнат или преместен.",
    "go_back": "Назад",
    "language": "Език",
},

  tr: {
    "check_order_status": "Sipariş durumunu kontrol et",
    "free_delivery": "€30 üzeri ücretsiz kargo",
    
    "search_placeholder": "Kitap, yazar, kategori ara...",
    "search": "Ara",
    
    "books": "Kitaplar",
    "art": "Sanat",
    "handmade": "El Yapımı",
    "ebooks": "E-kitaplar",
    "audiobooks": "Sesli Kitaplar",
    "other_products": "Diğer Ürünler",
    "gift_tips": "Hediye Önerileri",
    "gift_voucher": "Hediye çeki",
    "cart": "Sepet",
    
    "hi": "Merhaba",
    
    "books_title": "175 dilde 16 386 577 kitap",
    "ebooks_title": "İndirilecek 1 245 000 e-kitap",
    "audiobooks_title": "Kulaklarınız için 450 000 sesli kitap",
    "art_title": "Benzersiz Sanat Eserlerini Keşfedin",
    "help_text": "Ne seçeceğinizi bilmiyor musunuz? Size yardımcı olmak için buradayız!",
    "buy_now": "Şimdi al",

    "books_in_english": "İngilizce Kitaplar",
    "books_in_turkish": "Türkçe Kitaplar",
    "books_in_romanian": "Rumence Kitaplar",
    "books_in_bulgarian": "Bulgarca Kitaplar",

    "ebooks_in_turkish": "Türkçe E-kitaplar",
    "ebooks_in_english": "İngilizce E-kitaplar",
    "ebooks_in_romanian": "Rumence E-kitaplar",
    "ebooks_in_bulgarian": "Bulgarca E-kitaplar",

    "audiobooks_in_turkish": "Türkçe Sesli Kitaplar",
    "audiobooks_in_english": "İngilizce Sesli Kitaplar",
    "audiobooks_in_romanian": "Rumence Sesli Kitaplar",
    "audiobooks_in_bulgarian": "Bulgarca Sesli Kitaplar",

    "calendar_diary": "Takvim/Günlük",
    "audio": "Ses",
    "game_toy": "Oyun/Oyuncak",
    "video": "Video",
    "printed_items": "Basılı ürünler",
    "stationery": "Kırtasiye",
    "digital": "Dijital",

    "gifts_for_women": "Kadınlara hediyeler",
    "gifts_for_men": "Erkeklere hediyeler",
    "gifts_for_girls": "Kızlara hediyeler",
    "gifts_for_boys": "Erkek çocuklara hediyeler",
    "gifts_for_children": "Çocuklara hediyeler",

    "painting": "Resim",
    "sculpture": "Heykel",
    "music": "Müzik",
    "crafts": "El Sanatları",

    "be_whoever": "İstediğin Kişi Ol",
    "worlds_widest_selection": "DÜNYANIN EN GENİŞ KİTAP SEÇKİSİ",
    "all_the_books": "Dünyadaki tüm kitaplar",
    "all_about_shopping": "Alışveriş hakkında her şey",
    
    "terms_conditions": "Şartlar ve koşullar",
    "about_the_shop": "Mağaza hakkında",
    "who_we_are": "Biz kimiz",
    "contacts": "İletişim",
    "books_sustainability": "Kitapların sürdürülebilirliği",
    "for_customers": "Müşteriler için",
    "loyalty_programme": "Sadakat programı",
    "order_status": "Sipariş durumu",
    "returns_complaints": "İadeler / Şikayetler",
    "lets_stay_together": "Birlikte kalalım",
    
    "buy_book": "Kitap al",
    "video_btn": "Video",
    
    "23_million_titles": "23 milyon kitap",
    "in_150_languages": "150'den fazla dilde",
    "great_prices": "Harika fiyatlar",
    "always_up_to_date": "her zaman güncel",
    "libroamanto_club": "LIBROAMANTO kulübü",
    "full_of_gifts": "hediyelerle dolu",
    "2_million_customers": "2 milyon müşteri",
    "served_every_year": "her yıl hizmet verilen",
    
    "explore_categories": "Kategorileri Keşfet",
    "classic_modern_print": "Klasik ve Modern Baskı",
    "digital_reading_exp": "Dijital Okuma Deneyimi",
    "listen_to_stories": "Hikayelerinizi Dinleyin",
    "gifts_category": "Hediyeler",
    "special_items_lovers": "Aşıklar için Özel Ürünler",
    "view_collection": "Koleksiyonu Gör",

    "new_arrivals": "Yeni Gelenler",
    "freshly_added": "Koleksiyonumuza yeni eklenenler",
    "bestsellers": "Çok Satanlar",
    "most_loved_books": "Okurlarımız tarafından en çok sevilen kitaplar",
    "book_set_of_month": "AYIN KİTAP SETİ",
    "carefully_selected": "Bu ay için özenle seçilmiş kitaplar",
    "award_winning_books": "ÖDÜLLÜ KİTAPLAR",
    "critically_acclaimed": "Eleştirmenlerce beğenilen ve ödüllü edebiyat",
    "world_literature": "Dünya Edebiyatı",
    "timeless_classics": "Dünyanın dört bir yanından zamansız klasikler",
    "only": "Sadece",
    "left": "kaldı!",
    "unknown_author": "Bilinmeyen Yazar",

    "join_the": "Katıl",
    "club": "Kulübüne",
    "promo_desc": "Özel indirimler, yeni çıkanlara erken erişim ve ilk siparişinizde ücretsiz kargo fırsatı yakalayın!",
    "enter_email": "E-posta adresinizi girin",
    "join_now": "Şimdi Katıl",
    "promo_terms": "Katılarak, Şartlar ve Koşullarımızı ve Gizlilik Politikamızı kabul etmiş olursunuz",

    "ai_greeting": "Merhaba! 📚 Ben blendartbook AI, kişisel kitap asistanınız. Harika kitaplar keşfetmenize, zevkinize göre kitap önermeme veya kütüphanemiz hakkındaki sorularınızı yanıtlamama yardımcı olabilirim. Bugün ne arıyorsunuz?",
    "recommend_book": "📖 Kitap öner",
    "popular_genres": "🎭 Popüler türler",
    "gift_ideas": "🎁 Hediye fikirleri",
    "ask_me_about": "Bana kitaplar hakkında soru sor...",
    "powered_by": "blendartbook AI tarafından desteklenmektedir ✨",
    "properties": "Özellikler",
    "price_up_to": "Fiyat: maks €",
    "items_found": "ürün bulundu",
    "sort_by_popularity": "Sırala: Popülerlik",
    "no_products_found": "Ürün bulunamadı.",
    "english": "İngilizce",
    "turkish": "Türkçe",
    "romanian": "Rumence",
    "bulgarian": "Bulgarca",
    "all": "Tümü",
    "audio_filters": "Ses Filtreleri",
    "max_price": "Maks Fiyat: €",
    "audio_library": "Ses Kütüphanesi:",
    "syncing": "Senkronize ediliyor...",
    "tuning_frequencies": "Frekanslar ayarlanıyor...",
    "no_audiobooks_found": "Kriterlerinize uygun sesli kitap bulunamadı.",
    "browsing": "İnceleniyor:",
    "no_products_collection": "Bu koleksiyonda ürün bulunamadı.",
    "error_label": "Hata:",
    "all_products": "Tüm Ürünler",
    "set_new_password": "Yeni şifrenizi belirleyin",
    "reset_your_password": "Şifrenizi sıfırlayın",
    "welcome_back": "Tekrar hoş geldiniz",
    "create_an_account": "Hesap Oluştur",
    "choose_secure_password": "Güvenli bir şifre seçin ve kaydedin.",
    "email_reset_link": "Size bir şifre sıfırlama bağlantısı göndereceğiz.",
    "enter_details_access": "Hesabınıza erişmek için bilgilerinizi girin.",
    "join_track_orders": "Siparişlerinizi takip etmek için bize katılın.",
    "check_your_email": "E-postanızı kontrol edin!",
    "if_account_exists": "Eğer hesap varsa:",
    "receive_reset_link": "kısa süre içinde bir bağlantı alacaksınız.",
    "return_to_login": "Girişe Dön",
    "sent_confirmation_link": "Onay bağlantısı gönderdik:",
    "click_verify_account": "Hesabınızı doğrulamak için tıklayın.",
    "full_name": "Ad Soyad",
    "phone_number": "Telefon Numarası",
    "email_address": "E-posta Adresi",
    "password_label": "Şifre",
    "forgot_password": "Şifremi unuttum?",
    "at_least_6_chars": "En az 6 karakter",
    "new_password": "Yeni Şifre",
    "confirm_password": "Şifreyi Onayla",
    "repeat_new_password": "Yeni şifreyi tekrarla",
    "update_password": "Şifreyi Güncelle",
    "send_reset_link": "Bağlantıyı Gönder",
    "log_in": "Giriş Yap",
    "create_account_btn": "Hesap Oluştur",
    "back_to_login": "Girişe Dön",
    "dont_have_account": "Hesabınız yok mu?",
    "already_have_account": "Zaten bir hesabınız var mı?",
    "sign_up_free": "Ücretsiz üye ol",
    "log_in_here": "Buradan giriş yap",

    "my_account": "Hesabım",
    "profile_details": "Profil Detayları",
    "my_orders": "Siparişlerim",
    "log_out": "Çıkış Yap",
    "shipping_contact_details": "Teslimat ve İletişim Bilgileri",
    "profile_updated_success": "Profil başarıyla güncellendi!",
    "delivery_address": "Teslimat Adresi",
    "saving": "Kaydediliyor...",
    "save_changes": "Değişiklikleri Kaydet",
    "no_orders_yet": "Henüz sipariş vermediniz.",
    "delivered": "Teslim Edildi",
    "in_transit": "Yolda",
    "order_items": "Sipariş Öğeleri",
    "qty": "Adet:",
    "total": "Toplam:",
    "status": "Durum:",
    "john_doe": "Ahmet Yılmaz",

    "set_new_password_title": "Yeni şifre belirle",
    "enter_new_password_desc": "Hesabınız için yeni bir şifre girin.",
    "missing_expired_link": "Bu bağlantı eksik veya süresi dolmuş.",
    "go_to_signin": "Girişe Git",
    "password_updated": "Şifre güncellendi",
    "can_signin_new_password": "Artık yeni şifrenizle giriş yapabilirsiniz.",
    "continue_to_signin": "Giriş Yapmaya Devam Et",
    "repeat_password": "Şifreyi tekrarla",
    "payment_successful": "Ödeme başarılı",
    "payment_received_desc": "Teşekkür ederiz. Ödemeniz alındı ve güvenli bir şekilde işlendi.",
    "order_number": "Sipariş Numarası",
    "estimated_delivery": "Siparişiniz 5-6 gün içinde size ulaşacaktır.",
    "continue_shopping": "Alışverişe devam et",
    "back_to_cart": "Sepete Geri Dön",
      "shopping_hero_desc": "BlendArtBook'taki alışveriş deneyiminiz hakkında bilmeniz gereken her şey. Deneyiminizi sorunsuz, güvenli ve ilham verici kılmak için çalışıyoruz.",
    "easy_ordering": "Kolay Sipariş",
    "easy_ordering_desc": "Favori kitaplarınızı veya sanat eserlerinizi tek tıkla sepetinize ekleyin. Ödeme sürecimiz hız ve netlik için optimize edilmiştir.",
    "secure_payments": "Güvenli Ödemeler",
    "secure_payments_desc": "Verilerinizin her zaman güvende olmasını sağlamak için endüstri lideri şifreleme (SSL) ve Stripe ve Revolut gibi güvenilir ödeme ağ geçitlerini kullanıyoruz.",
    "fast_processing": "Hızlı İşleme",
    "fast_processing_desc": "Siparişler 24 saat içinde işleme alınır. Paketiniz depomuzdan çıkar çıkmaz bir takip numarası alacaksınız.",
    "cust_support_desc": "Destek ekibimiz, siparişiniz veya ürünlerimizle ilgili sorularınızda size yardımcı olmak için sohbet ve e-posta yoluyla hizmetinizdedir.",
    "how_to_shop": "Nasıl alışveriş yapılır?",
    "how_to_shop_desc": "Koleksiyonumuza göz atmak kolaydır. Belirli başlıkları bulmak için arama çubuğunu kullanabilir veya ana menüden seçilmiş kategorilerimizi keşfedebilirsiniz.",
    "tracking_order": "Sipariş takibi",
    "tracking_order_desc": "Sipariş verdikten sonra durumunu hesap panelinizden görüntüleyebilirsiniz. Ayrıca her aşamada otomatik e-posta güncellemeleri gönderiyoruz.",
    "need_help_order": "Siparişinizle ilgili yardıma mı ihtiyacınız var?",
    "support_experts_desc": "Destek uzmanlarımız ürünler, nakliye veya iadelerle ilgili her türlü sorunuzda size yardımcı olmaya hazırdır.",
    "contact_support": "Destekle İletişime Geç",
    "shipping_info": "Nakliye Bilgisi",
    "standard_delivery": "Standart Teslimat",
    "free_shipping_over": "30 € üzeri siparişlerde Ücretsiz Kargo",
    "payment_methods_title": "Ödeme Yöntemleri",
    "instant_confirmation": "Anında Onay",
    "mission_title": "Misyonumuz",
    "mission_desc": "Nadir sanat kitaplarına ve benzersiz el yapımı ürünlere erişimi demokratikleştirerek yaratıcılığın sınır tanımadığı bir dünya kurmak.",
    "email_us": "Bize E-posta Gönderin",
    "call_us": "Bizi Arayın",
    "visit_us": "Bizi Ziyaret Edin",
    "live_chat": "Canlı Sohbet",
    "terms_hero_desc": "Şeffaflık, adalet ve haklarınızın korunmasına yönelik taahhüdümüz.",
    "terms_section1_title": "1. Şartların Kabulü",
    "terms_section1_content": "BlendArtBook'a erişerek ve kullanarak, bu Şartlar ve Koşulları okuduğunuzu, anladığınızı ve bunlara bağlı kalmayı kabul ettiğinizi beyan edersiniz. Kabul etmiyorsanız lütfen hizmetlerimizi kullanmayın.",
    "terms_section2_title": "2. Gizlilik ve Veri",
    "terms_section2_content": "Gizliliğiniz bizim için her şeyden önemlidir. Tüm kişisel verileri Gizlilik Politikamıza ve ilgili uluslararası düzenlemelere (GDPR vb.) uygun olarak işliyoruz. Verilerinizi asla üçüncü taraflara satmıyoruz.",
    "terms_section3_title": "3. Fikri Mülkiyet",
    "terms_section3_content": "Metin, grafikler, logolar ve resimler dahil olmak üzere bu sitedeki tüm içerik BlendArtBook'un veya içerik sağlayıcılarının mülkiyetindedir ve uluslararası telif hakkı yasalarıyla korunmaktadır.",
    "terms_questions_title": "Şartlarımız hakkında sorularınız mı var?",
    "terms_questions_desc": "Politikalarımızdan herhangi biri hakkında açıklamaya ihtiyaç duyarsanız, ekibimiz daha ayrıntılı bilgi sağlamaktan mutluluk duyacaktır.",
    "who_we_are_hero_title": "Hikayeler yaratıyor, zihinlere ilham veriyoruz.",
    "who_we_are_hero_desc": "BlendArtBook basit bir tutkuyla doğdu: dünyanın en güzel kitaplarını ve sanat eserlerini meraklı okurlar ve sanatseverlerden oluşan küresel bir topluluğa sunmak.",
    "curated_with_love": "Sevgiyle Seçildi",
    "quality_first": "Önce Kalite",
    "contacts_hero_desc": "Size yardımcı olmak için buradayız. Bu kanallardan herhangi biri aracılığıyla bize ulaşın.",
    "live_chat_desc": "Acil yardıma mı ihtiyacınız var? Yapay zeka asistanımız ve destek ekibimiz 7/24 hizmetinizdedir.",
    "start_conversation": "Sohbet Başlat",
    "sustainability_desc": "Gezegenimize olan bağlılığımız ve sorumlu yayıncılık.",
    "sustainability_content": "Sanat ve edebiyat dünyası için sürdürülebilir bir geleceğe inanıyoruz. Kağıtlarımızı FSC sertifikalı ormanlardan temin ediyor ve mümkün olduğunca çevre dostu mürekkepler kullanıyoruz.",
    "loyalty_desc": "En tutkulu okurlarımızı ve koleksiyoncularımızı ödüllendiriyoruz.",
    "loyalty_content": "Her satın alma işleminizde puan kazanmak için BlendArtBook Sadakat Programına katılın. Puanlar özel indirimler ve ücretsiz kargo için kullanılabilir.",
    "returns_desc": "Memnuniyetiniz için sorunsuz iadeler ve özel destek.",
    "returns_content": "Satın aldığınız üründen memnun kalmadınız mı? Sorun değil. Orijinal durumundaki tüm ürünler için 30 günlük iade politikası sunuyoruz.",
    "still_have_questions": "Hala sorularınız mı var?",
    "support_team_desc": "Özel destek ekibimiz, bu konuyla ilgili diğer detaylarda size yardımcı olmaya hazırdır.",
    "cookies": "Çerezler",
    "privacy": "Gizlilik",
    "accessibility": "Erişilebilirlik",
    "delivery_hero_desc": "Huzurunuz için güvenilir nakliye ve güvenli ödeme yöntemleri.",
    "standard_delivery_desc": "Avrupa genelinde 3-5 iş günü.",
    "worldwide_shipping": "Dünya Çapında Nakliye",
    "credit_debit_cards": "Kredi/Banka Kartları",
    "revolut_pay": "Revolut Ödeme",
    "art_street_address": "123 Sanat Sokağı, Londra, Birleşik Krallık",
    "delivery_payment": "Teslimat ve ödeme",
    "shopping_cart": "Alışveriş Sepeti",
    "order_summary": "Sipariş Özeti",
    "product_label": "Ürün",
    "number_label": "Adet",
    "stock_availability": "Stok Durumu",
    "gift_wrapping": "Hediye Paketi",
    "price_label": "Fiyat",
    "cart_empty": "Sepetiniz boş.",
    "in_stock": "Stokta var",
    "shipping_24h": "24 saat içinde kargo",
    "select_option": "Seçiniz",
    "gift_wrap_yes": "Evet (+2.00 €)",
    "have_coupon": "İndirim kuponunuz mu var?",
    "coupon_placeholder": "Kod...",
    "apply_btn": "Uygula",
    "remove_btn": "Kaldır",
    "example_codes": "Örnek kodlar:",
    "subtotal_label": "Ara toplam:",
    "total_price_label": "Toplam fiyat:",
    "back_to_shop": "Mağazaya geri dön",
    "proceed_to_checkout": "Teslimat ve ödemeye geç",
    "discount_label": "indirim",
    "book_label": "Kitap",
    "secure_checkout": "Güvenli Ödeme",
    "delivery_payment_title": "Teslimat ve Ödeme",
    "back_to_cart": "Sepete geri dön",
    "payment_method": "Ödeme yöntemi",
    "promo_voucher_optional": "Promosyon kodu / kupon (isteğe bağlı)",
    "promo_empty_continue": "Kodunuz yok mu? Boş bırakıp devam edin.",
    "save_card_future": "Bu kartı gelecek ödemeler için kaydet",
    "i_accept": "Kabul ediyorum",
    "distance_sales_agreement": "Mesafeli Satış Sözleşmesi",
    "refund_cancellation": "İade ve İptal Koşulları",
    "and_conjunction": "ve",
    "kvkk_notice": "KVKK Aydınlatma Metni",
    "redirecting_revolut": "Revolut'a yönlendiriliyor...",
    "pay_with_revolut": "Revolut ile Öde",
    "revolut_instruction": "Gerçek kart ödemeleri ve cüzdan yöntemleri için Revolut ödeme sayfası.",
    "preparing_payment": "Güvenli ödeme hazırlanıyor...",
    "open_card_form": "Kart bilgilerini gir",
    "card_form_click_instruction": "Kart numarası, son kullanma tarihi ve CVV girmek için 'Kart bilgilerini gir' butonuna tıklayın.",
    "saved_cards_email": "Bu e-posta için kayıtlı kartlar",
    "refresh_btn": "Yenile",
    "no_saved_cards": "Henüz kayıtlı kart yok.",
    "loading_cards": "Kartlar yükleniyor...",
    "no_items_cart": "Henüz sepette ürün yok.",
    "order_save_error": "Sipariş kaydedilemedi. Lütfen tekrar deneyin.",
    "payment_failed": "Ödeme başarısız. Lütfen tekrar deneyin.",
    "processing_payment": "Ödeme işleniyor...",
    "pay_now": "Şimdi öde",
    "card_form_instruction": "Stripe tarafından desteklenen güvenli ödeme.",
    "saving_order": "Sipariş kaydediliyor...",
    "continue_pod": "Kapıda ödeme ile devam et",
    "stripe_not_configured": "Çevrimiçi kart ödemesi henüz yapılandırılmadı. Etkinleştirmek için anahtarları ekleyin.",
    "payment_successful": "Ödeme başarılı!",
    "payment_received_desc": "Siparişiniz alındı ve işleniyor. Kısa süre içinde bir onay e-postası alacaksınız.",
    "estimated_delivery": "Tahmini teslimat: 2-5 iş günü.",
    "items_count_label": "ürün",
    "confirmation_sent_to": "Onay şuraya gönderildi",
    "preparing_order_summary": "Sipariş özeti hazırlanıyor...",
    "order_details_not_found": "Sipariş detayları bulunamadı.",
    "go_back_home": "Ana sayfaya dön",
    "continue_shopping": "Alışverişe devam et",
    "order_number_label": "Sipariş numarası",
    "qty_label": "Adet",
    "author_label": "Yazar",
    "publisher_label": "Yayınevi",
    "add_to_library": "Kitaplığıma Ekle",
    "in_basket": "Sepette",
    "all_formats": "Tüm Formatlar",
    "paperback": "İnce Kapak",
    "estimated_shipping": "Tahmini Kargoya Verilme Tarihi",
    "free_shipping_promo": "30 € üzeri ücretsiz kargo",
    "featured_info": "Öne Çıkan Bilgiler",
    "paper_type": "Hamur Tipi",
    "page_count": "Sayfa Sayısı",
    "dimensions": "Ebat",
    "first_edition_year": "İlk Baskı Yılı",
    "edition_number": "Baskı Sayısı",
    "see_all_features": "Tüm Özellikleri Gör",
    "add_to_cart": "Sepete Ekle",
    "out_of_stock": "Stokta Yok",
    "added": "Eklendi!",
    "back_to_shop": "Mağazaya geri dön",
    "product_description_tab": "Ürün Açıklaması",
    "reviews_tab": "Değerlendirme",
    "returns_tab": "İptal ve İade",
    "reviews_count": "Değerlendirme",
    "show_more_reviews": "Daha Fazla Yorum Göster",
    "no_reviews_yet": "Bu ürün için henüz yorum yapılmamış.",
    "cancellation_faq_1": "Siparişimi nasıl iptal edebilirim?",
    "cancellation_faq_2": "Aldığım ürünü nasıl iade edebilirim?",
    "cancellation_faq_3": "Siparişimde yer alan bir veya birkaç ürünü iptal edebilir miyim?",
    "cancellation_faq_4": "Havale ile oluşturduğum ve henüz onaylanmayan siparişimi iptal edebilir miyim?",
    "cancellation_faq_5": "İptal edilen hediye kartımı aktif hale getirebilir miyim?",
    "cancellation_faq_6": "İptal edilen siparişimde hediye kartı kullandıysam, iptal edilen tutar kartıma yüklenir mi?",
    "cancellation_faq_7": "İptal talep ettiğim ürün/ürünler kargoya verilmiş ise ne yapabilirim?",
    "cancellation_ans_1": "Siparişinizi kargoya verilmeden önce 'Siparişlerim' bölümünden iptal edebilirsiniz. Kargo sürecine girmişse, teslim aldıktan sonra iade edebilirsiniz.",
    "cancellation_ans_2": "Ürünleri teslim aldığınız tarihten itibaren 14 gün içinde iade edebilirsiniz. İade talebi oluşturup kargo kodu ile geri göndermeniz yeterlidir.",
    "cancellation_ans_3": "Evet, henüz kargoya hazırlanmamış ürünleri tek tek seçerek iptal edebilirsiniz.",
    "cancellation_ans_4": "Evet, ödemesi onaylanmamış havale siparişlerinizi yönetim ekranından kolayca iptal edebilirsiniz.",
    "cancellation_ans_5": "İptal edilen siparişteki hediye kartları genellikle otomatik olarak tekrar tanımlanır veya e-posta ile yeni kod iletilir.",
    "cancellation_ans_6": "Evet, hediye kartı ile ödenen tutar kart bakiyenize veya yeni bir indirim kodu olarak iade edilir.",
    "cancellation_ans_7": "Kargo süreci başlamışsa iptal yapılamaz. Teslimat sırasında ürünü kabul etmeyebilir veya teslim aldıktan sonra iade yapabilirsiniz.",
    "default_description": "Bu kitap hakkında detaylı açıklama yakında eklenecektir.",
    "from_promo_bulletin": "(Tanıtım Bülteninden)",
    "paper_type_default": "2. Hamur",
    "edition_default": "1. Basım",
    "turkish": "Türkçe",
    "book_name_label": "Kitap Adı",
    "review_1_comment": "Mükemmellllll bir kitappp",
    "review_2_comment": "O kadar güzel bir kitap ki içinden ayracı bile çıktı çok beğendim öneririm",
    "review_3_comment": "Oğlumla beraber keyifle ve bol bol gülerek okuyoruz. Türkçe açısından kullanılan kelime ve deyimlerle de çocuklara katkı sağlıyor.",
    "write_review": "Yorum Yaz",
    "your_name": "Adınız",
    "your_rating": "Puanınız",
    "your_comment": "Yorumunuz",
    "submit_review": "Yorumu Gönder",
    "review_submitted_msg": "Teşekkürler! Yorumunuz onaylanmak üzere gönderildi.",
    "cancel_btn": "İptal",
    "lang_code": "tr-TR",
    "product_not_found": "Ürün Bulunamadı",
    "product_not_found_desc": "Aradığınız ürün yayından kaldırılmış veya taşınmış olabilir.",
    "go_back": "Geri Dön",
    "language": "Dil",
},

  ro: {
    "check_order_status": "Verifică starea comenzii",
    "free_delivery": "Livrare gratuită peste €30",
    
    "search_placeholder": "Caută cărți, autori, categorii...",
    "search": "Caută",
    
    "books": "Cărți",
    "art": "Artă",
    "handmade": "Handmade",
    "ebooks": "E-book-uri",
    "audiobooks": "Audiobook-uri",
    "other_products": "Alte produse",
    "gift_tips": "Sfaturi cadouri",
    "gift_voucher": "Voucher cadou",
    "cart": "Coș",
    
    "hi": "Salut",
    
    "books_title": "16 386 577 de cărți în 175 de limbi",
    "ebooks_title": "1 245 000 de e-book-uri de descărcat",
    "audiobooks_title": "450 000 de audiobook-uri pentru urechile tale",
    "art_title": "Explorează piese de artă unice",
    "help_text": "Nu știi ce să alegi? Suntem aici să te ajutăm!",
    "buy_now": "Cumpără acum",

    "books_in_english": "Cărți în engleză",
    "books_in_turkish": "Cărți în turcă",
    "books_in_romanian": "Cărți în română",
    "books_in_bulgarian": "Cărți în bulgară",

    "ebooks_in_turkish": "E-book-uri în turcă",
    "ebooks_in_english": "E-book-uri în engleză",
    "ebooks_in_romanian": "E-book-uri în română",
    "ebooks_in_bulgarian": "E-book-uri în bulgară",

    "audiobooks_in_turkish": "Audiobook-uri în turcă",
    "audiobooks_in_english": "Audiobook-uri în engleză",
    "audiobooks_in_romanian": "Audiobook-uri în română",
    "audiobooks_in_bulgarian": "Audiobook-uri în bulgară",

    "calendar_diary": "Calendar/Jurnal",
    "audio": "Audio",
    "game_toy": "Joc/Jucărie",
    "video": "Video",
    "printed_items": "Articole tipărite",
    "stationery": "Papetărie",
    "digital": "Digital",

    "gifts_for_women": "Cadouri pentru femei",
    "gifts_for_men": "Cadouri pentru bărbați",
    "gifts_for_girls": "Cadouri pentru fete",
    "gifts_for_boys": "Cadouri pentru băieți",
    "gifts_for_children": "Cadouri pentru copii",

    "painting": "Pictură",
    "sculpture": "Sculptură",
    "music": "Muzică",
    "crafts": "Meșteșuguri",

    "be_whoever": "Fii Cine Vrei",
    "worlds_widest_selection": "CEA MAI LARGĂ SELECȚIE DE CĂRȚI DIN LUME",
    "all_the_books": "Toate cărțile din lume",
    "all_about_shopping": "Totul despre cumpărături",
    
    "terms_conditions": "Termeni și condiții",
    "about_the_shop": "Despre magazin",
    "who_we_are": "Cine suntem",
    "contacts": "Contacte",
    "books_sustainability": "Sustenabilitatea cărților",
    "for_customers": "Pentru clienți",
    "loyalty_programme": "Program de loialitate",
    "order_status": "Starea comenzii",
    "returns_complaints": "Retururi / Reclamații",
    "lets_stay_together": "Să rămânem împreună",
    
    "buy_book": "Cumpără carte",
    "video_btn": "Video",
    
    "23_million_titles": "23 milioane de titluri",
    "in_150_languages": "în 150+ limbi",
    "great_prices": "Prețuri excelente",
    "always_up_to_date": "mereu actualizate",
    "libroamanto_club": "Clubul LIBROAMANTO",
    "full_of_gifts": "plin de cadouri",
    "2_million_customers": "2 milioane de clienți",
    "served_every_year": "serviți în fiecare an",
    
    "explore_categories": "Explorează categoriile",
    "classic_modern_print": "Tipărit clasic și modern",
    "digital_reading_exp": "Experiență de citire digitală",
    "listen_to_stories": "Ascultă poveștile tale",
    "gifts_category": "Cadouri",
    "special_items_lovers": "Articole speciale pentru îndrăgostiți",
    "view_collection": "Vezi colecția",

    "new_arrivals": "Noutăți",
    "freshly_added": "Proaspăt adăugate în colecția noastră",
    "bestsellers": "Bestselleruri",
    "most_loved_books": "Cele mai iubite cărți de cititorii noștri",
    "book_set_of_month": "SETUL DE CĂRȚI AL LUNII",
    "carefully_selected": "Cărți selectate cu grijă pentru această lună",
    "award_winning_books": "CĂRȚI PREMIATE",
    "critically_acclaimed": "Literatură apreciată critic și celebrată",
    "world_literature": "Literatură universală",
    "timeless_classics": "Clasici atemporali din întreaga lume",
    "only": "Doar",
    "left": "rămase!",
    "unknown_author": "Autor necunoscut",

    "join_the": "Alătură-te",
    "club": "Clubului",
    "promo_desc": "Obține reduceri exclusive, acces anticipat la noi lansări și livrare gratuită la prima ta comandă!",
    "enter_email": "Introdu adresa ta de email",
    "join_now": "Alătură-te acum",
    "promo_terms": "Prin înscriere, ești de acord cu Termenii și Condițiile și cu Politica de confidențialitate",

    "ai_greeting": "Salut! 📚 Sunt blendartbook AI, asistentul tău personal pentru cărți. Te pot ajuta să descoperi cărți uimitoare, să îți recomand lecturi în funcție de gustul tău sau să îți răspund la orice întrebare despre biblioteca noastră. Ce cauți astăzi?",
    "recommend_book": "📖 Recomandă o carte",
    "popular_genres": "🎭 Genuri populare",
    "gift_ideas": "🎁 Idei de cadouri",
    "ask_me_about": "Întreabă-mă despre cărți...",
    "powered_by": "Powered by blendartbook AI ✨",
    "properties": "Proprietăți",
    "price_up_to": "Preț: până la €",
    "items_found": "produse găsite",
    "sort_by_popularity": "Sortare: Popularitate",
    "no_products_found": "Niciun produs găsit.",
    "english": "Engleză",
    "turkish": "Turcă",
    "romanian": "Română",
    "bulgarian": "Bulgară",
    "all": "Toate",
    "audio_filters": "Filtre audio",
    "max_price": "Preț maxim: €",
    "audio_library": "Bibliotecă audio:",
    "syncing": "Se sincronizează...",
    "tuning_frequencies": "Ajustare frecvențe...",
    "no_audiobooks_found": "Nicio carte audio nu corespunde criteriilor tale.",
    "browsing": "Navigare:",
    "no_products_collection": "Nu au fost găsite produse în această colecție.",
    "error_label": "Eroare:",
    "all_products": "Toate produsele",
    "set_new_password": "Setați o parolă nouă",
    "reset_your_password": "Resetați parola",
    "welcome_back": "Bine ai revenit",
    "create_an_account": "Creează un cont",
    "choose_secure_password": "Alegeți o parolă sigură și salvați-o.",
    "email_reset_link": "Vă vom trimite un link de resetare.",
    "enter_details_access": "Introduceți detaliile pentru a accesa contul.",
    "join_track_orders": "Alăturați-vă pentru a urmări comenzile.",
    "check_your_email": "Verificați emailul!",
    "if_account_exists": "Dacă există un cont pentru",
    "receive_reset_link": "veți primi un link în scurt timp.",
    "return_to_login": "Înapoi la Autentificare",
    "sent_confirmation_link": "Am trimis un link de confirmare către",
    "click_verify_account": "Vă rugăm să dați clic pentru a verifica contul.",
    "full_name": "Nume Complet",
    "phone_number": "Număr de telefon",
    "email_address": "Adresă de Email",
    "password_label": "Parolă",
    "forgot_password": "Ați uitat parola?",
    "at_least_6_chars": "Cel puțin 6 caractere",
    "new_password": "Parolă Nouă",
    "confirm_password": "Confirmați Parola",
    "repeat_new_password": "Repetați parola nouă",
    "update_password": "Actualizează Parola",
    "send_reset_link": "Trimite Link",
    "log_in": "Autentificare",
    "create_account_btn": "Creează Cont",
    "back_to_login": "Înapoi la Autentificare",
    "dont_have_account": "Nu ai cont?",
    "already_have_account": "Ai deja un cont?",
    "sign_up_free": "Înscrie-te gratuit",
    "log_in_here": "Autentifică-te aici",

    "my_account": "Contul meu",
    "profile_details": "Detalii profil",
    "my_orders": "Comenzile mele",
    "log_out": "Deconectare",
    "shipping_contact_details": "Detalii de livrare",
    "profile_updated_success": "Profil actualizat cu succes!",
    "delivery_address": "Adresa de livrare",
    "saving": "Se salvează...",
    "save_changes": "Salvează",
    "no_orders_yet": "Nu ai plasat nicio comandă încă.",
    "delivered": "Livrat",
    "in_transit": "În tranzit",
    "order_items": "Articole",
    "qty": "Cantitate:",
    "total": "Total:",
    "status": "Stare:",
    "john_doe": "Ion Popescu",

    "set_new_password_title": "Setați o parolă nouă",
    "enter_new_password_desc": "Introduceți o nouă parolă pentru contul dvs.",
    "missing_expired_link": "Acest link a expirat sau lipsește.",
    "go_to_signin": "Mergi la Autentificare",
    "password_updated": "Parolă actualizată",
    "can_signin_new_password": "Acum vă puteți autentifica cu noua parolă.",
    "continue_to_signin": "Continuă spre Autentificare",
    "repeat_password": "Repetați parola",
    "payment_successful": "Plată reușită",
    "payment_received_desc": "Vă mulțumim. Plata dumneavoastră a fost primită și procesată în siguranță.",
    "order_number": "Număr comandă",
    "estimated_delivery": "Comanda dumneavoastră va ajunge la dumneavoastră în 5-6 zile.",
    "continue_shopping": "Continuă cumpărăturile",
    "back_to_cart": "Înapoi la coș",
      "shopping_hero_desc": "Tot ce trebuie să știi despre experiența ta de cumpărături la BlendArtBook. Ne străduim să o facem fluidă, sigură și plină de inspirație.",
    "easy_ordering": "Comandă Ușoară",
    "easy_ordering_desc": "Adaugă cărțile sau piesele de artă preferate în coș cu un singur clic. Procesul nostru de finalizare este optimizat pentru viteză și claritate.",
    "secure_payments": "Plăți Securizate",
    "secure_payments_desc": "Folosim criptare de vârf (SSL) și porți de plată de încredere precum Stripe și Revolut pentru a ne asigura că datele tale sunt mereu în siguranță.",
    "fast_processing": "Procesare Rapidă",
    "fast_processing_desc": "Comenzile sunt procesate în 24 de ore. Vei primi un număr de urmărire imediat ce pachetul părăsește depozitul nostru.",
    "cust_support_desc": "Echipa noastră de asistență este disponibilă prin chat și e-mail pentru a te ajuta cu orice întrebări despre comandă sau produse.",
    "how_to_shop": "Cum să cumperi?",
    "how_to_shop_desc": "Navigarea prin colecția noastră este ușoară. Poți folosi bara de căutare sau poți explora categoriile noastre din meniul principal.",
    "tracking_order": "Urmărirea comenzii",
    "tracking_order_desc": "După plasarea unei comenzi, poți vedea starea acesteia în panoul de control al contului tău. Trimitem, de asemenea, actualizări prin e-mail.",
    "need_help_order": "Ai nevoie de ajutor cu comanda?",
    "support_experts_desc": "Experții noștri sunt gata să te ajute cu orice întrebări despre produse, livrare sau retururi.",
    "contact_support": "Contactează Asistența",
    "shipping_info": "Informații Livrare",
    "standard_delivery": "Livrare Standard",
    "free_shipping_over": "Livrare gratuită la comenzi peste 30 €",
    "payment_methods_title": "Metode de Plată",
    "instant_confirmation": "Confirmare Imediată",
    "mission_title": "Misiunea Noastră",
    "mission_desc": "Să democratizăm accesul la cărți de artă rare și obiecte handmade unice, promovând o lume în care creativitatea nu are granițe.",
    "email_us": "Trimite-ne un E-mail",
    "call_us": "Sună-ne",
    "visit_us": "Vizitează-ne",
    "live_chat": "Chat în Direct",
    "terms_hero_desc": "Angajamentul nostru față de transparență, corectitudine și protecția drepturilor dumneavoastră.",
    "terms_section1_title": "1. Acceptarea Termenilor",
    "terms_section1_content": "Prin accesarea și utilizarea BlendArtBook, recunoașteți că ați citit, înțeles și sunteți de acord să respectați acești Termeni și Condiții. Dacă nu sunteți de acord, vă rugăm să nu folosiți serviciile noastre.",
    "terms_section2_title": "2. Confidențialitate și Date",
    "terms_section2_content": "Confidențialitatea dumneavoastră este primordială. Gestionăm toate datele cu caracter personal în conformitate cu Politica noastră de Confidențialitate și reglementările internaționale relevante (GDPR etc.). Nu vindem niciodată datele dumneavoastră unor terțe părți.",
    "terms_section3_title": "3. Proprietate Intelectuală",
    "terms_section3_content": "Tot conținutul de pe acest site, inclusiv textul, grafica, logo-urile și imaginile, este proprietatea BlendArtBook sau a furnizorilor săi de conținut și este protejat de legile internaționale privind drepturile de autor.",
    "terms_questions_title": "Întrebări despre termenii noștri?",
    "terms_questions_desc": "Dacă aveți nevoie de clarificări cu privire la oricare dintre politicile noastre, echipa noastră este bucuroasă să vă ofere informații mai detaliate.",
    "who_we_are_hero_title": "Creăm povești, inspirăm minți.",
    "who_we_are_hero_desc": "BlendArtBook s-a născut dintr-o pasiune simplă: de a aduce cele mai frumoase cărți și piese de artă din lume unei comunități globale de cititori curioși și iubitori de artă.",
    "curated_with_love": "Curat cu Dragoste",
    "quality_first": "Calitatea pe Primul Loc",
    "contacts_hero_desc": "Suntem aici să te ajutăm. Contactează-ne prin oricare dintre aceste canale.",
    "live_chat_desc": "Ai nevoie de asistență imediată? Asistentul nostru AI și echipa de suport sunt disponibili 24/7.",
    "start_conversation": "Începe o Conversație",
    "sustainability_desc": "Angajamentul nostru față de planetă și publicarea responsabilă.",
    "sustainability_content": "Credem într-un viitor sustenabil pentru lumea artei și a literaturii. Ne aprovizionăm cu hârtie din păduri certificate FSC și folosim cerneluri ecologice ori de câte ori este posibil.",
    "loyalty_desc": "Recompensarea celor mai pasionați cititori și colecționari ai noștri.",
    "loyalty_content": "Alăturați-vă Programului de Loialitate BlendArtBook pentru a câștiga puncte la fiecare achiziție. Punctele pot fi răscumpărate pentru reduceri exclusive și transport gratuit.",
    "returns_desc": "Retururi fără bătăi de cap și asistență dedicată pentru satisfacția dumneavoastră.",
    "returns_content": "Nu sunteți mulțumit de achiziție? Nicio problemă. Oferim o politică de retur de 30 de zile pentru toate articolele în starea lor originală.",
    "still_have_questions": "Mai aveți întrebări?",
    "support_team_desc": "Echipa noastră dedicată de asistență este gata să vă ajute cu orice alte detalii referitoare la acest subiect.",
    "cookies": "Cookie-uri",
    "privacy": "Confidențialitate",
    "accessibility": "Accesibilitate",
    "delivery_hero_desc": "Livrare fiabilă și metode de plată sigure pentru liniștea dumneavoastră.",
    "standard_delivery_desc": "3-5 zile lucrătoare în toată Europa.",
    "worldwide_shipping": "Livrare în întreaga lume",
    "credit_debit_cards": "Carduri de Credit/Debit",
    "revolut_pay": "Plată Revolut",
    "art_street_address": "Strada Artelor nr. 123, Londra, Regatul Unit",
    "delivery_payment": "Livrare și plată",
    "shopping_cart": "Coș de cumpărături",
    "order_summary": "Sumar comandă",
    "product_label": "Produs",
    "number_label": "Număr",
    "stock_availability": "Disponibilitate stoc",
    "gift_wrapping": "Ambalare cadou",
    "price_label": "Preț",
    "cart_empty": "Coșul tău este gol.",
    "in_stock": "În stoc",
    "shipping_24h": "Expediere în 24 de ore",
    "select_option": "Selectează",
    "gift_wrap_yes": "Da (+2.00 €)",
    "have_coupon": "Ai un cupon de reducere?",
    "coupon_placeholder": "Cod...",
    "apply_btn": "Aplică",
    "remove_btn": "Elimină",
    "example_codes": "Coduri exemplu:",
    "subtotal_label": "Subtotal:",
    "total_price_label": "Preț total:",
    "back_to_shop": "Înapoi la magazin",
    "proceed_to_checkout": "Continuă către livrare și plată",
    "discount_label": "reducere",
    "book_label": "Carte",
    "secure_checkout": "Finalizare Securizată",
    "delivery_payment_title": "Livrare și Plată",
    "back_to_cart": "Înapoi la coș",
    "payment_method": "Metodă de plată",
    "promo_voucher_optional": "Cod promoțional / voucher (opțional)",
    "promo_empty_continue": "Nu ai un cod? Lasă gol și continuă.",
    "save_card_future": "Salvează acest card pentru plăți viitoare",
    "i_accept": "Accept",
    "distance_sales_agreement": "Contract de vânzare la distanță",
    "refund_cancellation": "Politica de retur și anulare",
    "and_conjunction": "și",
    "kvkk_notice": "Notă de confidențialitate",
    "redirecting_revolut": "Redirecționare către Revolut...",
    "pay_with_revolut": "Plătește cu Revolut",
    "revolut_instruction": "Pagină de plată Revolut pentru plăți cu cardul și metode de portofel digital.",
    "preparing_payment": "Se pregătește plata securizată...",
    "open_card_form": "Deschide formularul cardului",
    "card_form_click_instruction": "Apasă pe „Deschide formularul cardului” pentru a introduce numărul cardului, data expirării și CVV.",
    "saved_cards_email": "Carduri salvate pentru acest email",
    "refresh_btn": "Actualizează",
    "no_saved_cards": "Nu există carduri salvate încă.",
    "loading_cards": "Se încarcă cardurile...",
    "no_items_cart": "Nu există produse în coș încă.",
    "order_save_error": "Comanda nu a putut fi salvată. Vă rugăm să încercați din nou.",
    "payment_failed": "Plata a eșuat. Vă rugăm să încercați din nou.",
    "processing_payment": "Se procesează plata...",
    "pay_now": "Plătește acum",
    "card_form_instruction": "Plată securizată prin Stripe.",
    "saving_order": "Se salvează comanda...",
    "continue_pod": "Continuă cu plata la livrare",
    "stripe_not_configured": "Plata online cu cardul nu este încă configurată. Adăugați cheile pentru a o activa.",
    "payment_successful": "Plată reușită!",
    "payment_received_desc": "Comanda dumneavoastră a fost primită și este în curs de procesare. Veți primi un e-mail de confirmare în curând.",
    "estimated_delivery": "Livrare estimată: 2-5 zile lucrătoare.",
    "items_count_label": "produse",
    "confirmation_sent_to": "Confirmarea a fost trimisă la",
    "preparing_order_summary": "Se pregătește rezumatul comenzii...",
    "order_details_not_found": "Detaliile comenzii nu au putut fi găsite.",
    "go_back_home": "Înapoi la pagina principală",
    "continue_shopping": "Continuă cumpărăturile",
    "order_number_label": "Număr comandă",
    "qty_label": "Cantitate",
    "author_label": "Autor",
    "publisher_label": "Editură",
    "add_to_library": "Adaugă în bibliotecă",
    "in_basket": "În coș",
    "all_formats": "Toate formatele",
    "paperback": "Copertă broșată",
    "estimated_shipping": "Data estimată de livrare",
    "free_shipping_promo": "Livrare gratuită peste 30 €",
    "featured_info": "Informații recomandate",
    "paper_type": "Tip de hârtie",
    "page_count": "Număr de pagini",
    "dimensions": "Dimensiuni",
    "first_edition_year": "Anul primei ediții",
    "edition_number": "Numărul ediției",
    "see_all_features": "Vezi toate dotările",
    "add_to_cart": "Adaugă în coș",
    "out_of_stock": "Stoc epuizat",
    "added": "Adăugat!",
    "back_to_shop": "Înapoi la magazin",
    "product_description_tab": "Descrierea produsului",
    "reviews_tab": "Recenzii",
    "returns_tab": "Retururi și anulări",
    "reviews_count": "Recenzii",
    "show_more_reviews": "Arată mai multe recenzii",
    "no_reviews_yet": "Nu existǎ recenzii pentru acest produs încǎ.",
    "cancellation_faq_1": "Cum îmi pot anula comanda?",
    "cancellation_faq_2": "Cum pot returna produsul primit?",
    "cancellation_faq_3": "Pot anula unul sau mai multe articole din comanda mea?",
    "cancellation_faq_4": "Pot anula o comandă prin transfer bancar care nu a fost încă aprobată?",
    "cancellation_faq_5": "Îmi pot reactiva cardul cadou anulat?",
    "cancellation_faq_6": "Dacă am folosit un card cadou în comanda mea anulată, suma va fi rambursată?",
    "cancellation_faq_7": "Ce pot face dacă produsele pe care am cerut să le anulez au fost expediate?",
    "cancellation_ans_1": "Vă puteți anula comanda din secțiunea 'Comenzile mele' înainte de a fi expediată. Dacă a fost deja expediată, o puteți returna după primire.",
    "cancellation_ans_2": "Puteți returna produsele în termen de 14 zile de la primire. Pur și simplu creați o cerere de retur și trimiteți-le înapoi cu codul de expediere furnizat.",
    "cancellation_ans_3": "Da, puteți selecta anumite articole de anulat atâta timp cât acestea nu au fost încă pregătite pentru expediere.",
    "cancellation_ans_4": "Da, comenzile prin transfer bancar pot fi anulate cu ușurință prin ecranul de gestionare a comenzilor înainte ca plata să fie procesată.",
    "cancellation_ans_5": "Cardurile cadou folosite în comenzile anulate sunt de obicei reactivate automat sau un nou cod este trimis pe e-mailul dvs.",
    "cancellation_ans_6": "Da, suma cheltuită de pe cardul cadou va fi rambursată înapoi în soldul cardului sau ca un nou cod de reducere.",
    "cancellation_ans_7": "Dacă procesul de expediere a început, anularea nu poate fi finalizată. Ar trebui să refuzați livrarea sau să o returnați după primire.",
    "default_description": "O descriere detaliată a acestei cărți va fi adăugată în curând.",
    "from_promo_bulletin": "(Din Buletinul de Promovare)",
    "paper_type_default": "Hârtie de calitate",
    "edition_default": "Prima ediție",
    "turkish": "Turcă",
    "book_name_label": "Numele cărții",
    "review_1_comment": "O carte excelentă!",
    "review_2_comment": "Atât de frumoasă, a venit chiar și cu un semn de carte. O recomand cu drag.",
    "review_3_comment": "O citim împreună cu fiul meu cu multă bucurie și râsete. Contribuie la dezvoltarea vocabularului copiilor.",
    "write_review": "Scrie o recenzie",
    "your_name": "Numele tău",
    "your_rating": "Evaluarea ta",
    "your_comment": "Comentariul tău",
    "submit_review": "Trimite recenzia",
    "review_submitted_msg": "Mulțumim! Recenzia ta a fost trimisă pentru aprobare.",
    "cancel_btn": "Anulează",
    "lang_code": "ro-RO",
    "product_not_found": "Produsul nu a fost găsit",
    "product_not_found_desc": "Produsul pe care îl căutați poate fi eliminat sau mutat.",
    "go_back": "Înapoi",
    "language": "Limbă",
},
};

// --- CONTEXT ---
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  currentLanguageOption: LanguageOption;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem("blendartbook-lang") as Language | null;
    if (saved && ["en", "bg", "tr", "ro"].includes(saved)) {
      setLanguageState(saved);
    }
    setMounted(true);
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("blendartbook-lang", lang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  }, [language]);

  const currentLanguageOption = LANGUAGES.find(l => l.code === language) || LANGUAGES[0];

  // Prevent hydration mismatch by rendering children only after mount
  if (!mounted) {
    return (
      <LanguageContext.Provider value={{ language: "en", setLanguage, t: (key: string) => translations["en"]?.[key] || key, currentLanguageOption: LANGUAGES[0] }}>
        {children}
      </LanguageContext.Provider>
    );
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguageOption }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
